### ISSUE TITLE
Cog should work in subdirectories

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#102]
Cog should search up the file tree for `cog.yaml`, like Keepsake does.

For example, if `/home/ben/hotdog-detector/cog.yaml` exists, then I should be able to run `cog predict` in `/home/ben/hotdog-detector/subdir/` and it should do what I expect.

There is some nuance here with `cog run`. Should the working directory be the relative current directory inside the container?

**Comment by synek** [comment]
Hey I've got a WIP branch for this and will open a PR soon for you to review.

**Comment by bfirsh** [comment]
Thanks for your help here @synek! Will consider this closed and open another issue for the `cog run` thing.
