### ISSUE TITLE
Windows 11 install docs incorrect

### ISSUE THREAD

**Issue by boxabirds** [replicate/cog#1024]
First issue is running `wsl.exe` not in administrator mode you do not get `sudo`

Second is this line

`sudo apt-get -y install cuda`

returns an error

`E: Unable to locate package cuda`

Instead run

`sudo apt-get -y install cuda-toolkit-11-7`

**Comment by mattt** [comment]
Thanks so much for your feedback, @boxabirds. I just opened https://github.com/replicate/cog/pull/1113, which makes these changes. Please let me know if you run into any other issues getting this work on Windows 😃
