### ISSUE TITLE
How to pulling Replicate docker image to local

### ISSUE THREAD

**Issue by ghtelpelight** [replicate/cog#1070]
How to use `docker pull` to pull a private Replicate docker image? I need this to debug some of my old images, which I don't have their local versions anymore

**Comment by mattt** [comment]
Hi @ghtelpelight. You can pull a Docker image using the instructions from a model's page on Replicate (for example, https://replicate.com/stability-ai/stable-diffusion/api).

```console
$ docker pull r8.im/daanelson/stable-diffusion-speed-lab@sha256:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf
```

You may need to authenticate with the `r8.im` registry first. To do that, run the following command:

```console
$ cog login
```
