### ISSUE TITLE
Extract functionality for determining CUDA-compatible package requirements into separate tool / command / library

### ISSUE THREAD

**Issue by mattt** [replicate/cog#1081]
Related to https://github.com/replicate/cog/issues/157

Part of Cog's secret sauce is its ability to resolve high-level Python package constraints into pre-compiled CUDA distributions. For example, for `torch` on CUDA 11.8, Cog generates the requirements `torch==2.0.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`.

Declaring package dependencies in `cog.yaml` works pretty well, but it's difficult to reconcile this approach for projects that use other tools for package management. For example, a project that declares its build system interface with [`pyproject.toml`](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/). It'd be nice for Cog to behave more like a modern standards-adhering packaging tool like [Setuptools](https://setuptools.pypa.io/), [Hatch](https://hatch.pypa.io/), or [flit](https://flit.pypa.io/), so that Cog's CUDA magic can compose with tools like [pip-compile](https://github.com/jazzband/pip-tools).

It'd be nice to have a `cog resolve` command (spelling TBD) that prints the list of requirements Cog will use to build the project. You could run that without doing `cog build`, write that to `requirements.txt` and then compose that with other tools for dependency management.

**Comment by bfirsh** [comment]
Something we were considering is just yanking out the compatibility matrix as a separate repo. Just a cleaned up version of those JSON files would be a big contribution to the ML community...

**Comment by rakesh-krishna** [comment]
it would bea  great help, amount of time we spend on installing and later figuring out some thing is incomapatable and try another version quickly adds up. This time could be better spent on debugging something else.
