### ISSUE TITLE
executor failed running [/bin/sh -c pip install -r /tmp/requirements.txt]: exit code: 2

### ISSUE THREAD

**Issue by zackzhy** [replicate/cog#1084]
When I run "cog predict", it takes so much time for "pip install". Is there any way I can change the "index_url" for pip so that I can speed up installation of third-party libraries by using pip?

**Comment by mattt** [comment]
Hi @zackzhy. `pip install` can take a long time to run, especially for large dependencies like PyTorch. We set `https://download.pytorch.org` as an extra index for installation, and install binary wheels when available. Do you have any suggestions for how this could run faster?

As far as changing the index URL used by pip, you can specify that in a `requirements.txt` file and pass that file path to the [`python_requirements` key in `cog.yaml`](https://github.com/replicate/cog/blob/2ab4e71174a71725ebf56ed82c8a1752ddb23a25/docs/yaml.md#python_requirements). If you need to authenticate with a private registry, we have documentation for doing that [here](https://github.com/replicate/cog/blob/2ab4e71174a71725ebf56ed82c8a1752ddb23a25/docs/private-package-registry.md).

**Comment by zackzhy** [comment]
Thanks a lot for your help! There's a noticeable increase in speed of pip after I specify the index URL in a requirements.txt file. I think that is fast enough
