### ISSUE TITLE
REGRESSION - cog no longer respects .dockerignore files

### ISSUE THREAD

**Issue by anotherjesse** [replicate/cog#1094]
cog will overwrites the `.dockerignore` file, which is used to ensure secrets, temp files, etc don't get added to the produced cog

steps to reproduce

1. checkout [cog-examples](https://github.com/replicate/cog-examples), go into `hello-world` example
2. create a directory called weights inside hello-world
3. create a weights file: `dd if=/dev/zero of=weights/zeros count=1024 bs=1024`
4. create a file to be ignored `dd if=/dev/zero of=ignored count=1024 bs=1024`
5. create ignore: `echo ignore_me > .dockerignore`
6. cog build
7. use `docker images` to find the last produced image
8. `docker run -ti 1f8bee0e60b4 /bin/bash` (where `1f8bee0e60b4` is the image id created by the build

expected: the produced docker image will not include `ignore_me`

actual: it includes it, and the .dockerignore file has been overwritten

both of which are not expected

**Comment by hongchaodeng** [comment]
This is my fault introduced in https://github.com/replicate/cog/pull/1041 😅
It will actually generate a new `.dockerignore` file to do some tricks.
Probably we can add the content into the intermediate `.dockerignore` and restore it afterwards.
I will try to submit a PR to fix it.
cc @mattt @anotherjesse

**Comment by anotherjesse** [comment]
hmm, @hongchaodeng perhaps should your intermediate content be appended then removed from .dockerignore?

**Comment by anotherjesse** [comment]
@hongchaodeng it is amazing how much faster #1041 makes cog!! Once a few of these unintended side effects are removed I think lots of power users of cog will love it!

**Comment by hongchaodeng** [comment]
@anotherjesse Yep. I will ask you to review once I submit the fix PR :)
