### ISSUE TITLE
Build fails when using `cog version 0.8.0-beta4`

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#1096]
<img width="1414" alt="image" src="https://github.com/replicate/cog/assets/713993/b67717dd-99be-40f6-a6d2-acd698ad9b85">

For some reason it's trying to pull the intermediate weights image from Docker Hub?

cc @hongchaodeng @mattt

**Comment by hongchaodeng** [comment]
Let me look into it.
Last time I tried it worked. There are new problems uncovered here. I will try to reproduce it first using https://github.com/andreasjansson/cog-musicgen-looper

**Comment by hongchaodeng** [comment]
Fix submitted: https://github.com/replicate/cog/pull/1097
I tried it locally and it worked. Also included tests.
cc @andreasjansson
