### ISSUE TITLE
Windows WSL2 implementation with Cloud GPU

### ISSUE THREAD

**Issue by InsightfulFuture** [replicate/cog#1129]
I want to use Replicate to deploy custom models for inference, but I'm Windows based. I read the documentation and saw this is possible with WSL2, but it mentions that you must have a GPU, install GPU drivers, etc. If I want to use Lambda Labs cloud GPUs is this still possible?

**Comment by mattt** [comment]
Hi @InsightfulFuture. We have a tutorial for pushing models with Lambda Labs here: https://replicate.com/docs/guides/get-a-gpu-machine. You should be able to SSH into a cloud GPU instance from WSL2 and push models to Replicate that way.
