### ISSUE TITLE
multiple tasks from cog command

### ISSUE THREAD

**Issue by frenchie1980** [replicate/cog#1158]
Is it possible to process multiple predict tasks from a single cog invocation? some predicts are so quick that firing up and shutting down the docker container can take 80-90% of the time

either by passing a json task list including multiple args per taks. I think I've seen reference to this somewhere, though I've lost track of the site.

or by passing a list of inputs perhaps

eg. 

```
cog predict r8.im/sczhou/codeformer@sha256:7de2ea26c616d5bf2245ad0d5e24f0ff9a6204578a5c876db53142edd9d2cd56 \
  -i tasks=@path/to/json_task_list  \
```
or
```
cog predict r8.im/sczhou/codeformer@sha256:7de2ea26c616d5bf2245ad0d5e24f0ff9a6204578a5c876db53142edd9d2cd56 \
  -i image=[@path/to/file, @path/to/file, @path/to/file]  \
  -i codeformer_fidelity=... \
```
or
```
cog predict r8.im/sczhou/codeformer@sha256:7de2ea26c616d5bf2245ad0d5e24f0ff9a6204578a5c876db53142edd9d2cd56 \
  -i image=@path/to/file \
  -i image=@path/to/file \
  -i image=@path/to/file \
  -i codeformer_fidelity=... \
```

relates to #612

**Comment by yorickvP** [comment]
This is currently possible by running the image from docker and then doing multiple curl requests:

https://replicate.com/sczhou/codeformer?input=docker
