### ISSUE TITLE
Cannot use --separate-weights flag

### ISSUE THREAD

**Issue by Elvenson** [replicate/cog#1178]
According to the [official documentation](https://github.com/replicate/cog/blob/main/docs/getting-started.md), we can use the `--separate-weights` flag to reduce the build docker time. But when I tried using it `cog build --separate-weights`, it raised the following error:
```
ⅹ unknown flag: --separate-weights
```

I have tried installing the latest cog version using the following command:
```
sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
sudo chmod +x /usr/local/bin/cog
```
But the problem persisted,

**Comment by hongchaodeng** [comment]
It's not officially released yet. Please download the beta version and try out :)
