### ISSUE TITLE
Error 413 when calling Meronym docker

### ISSUE THREAD

**Issue by GuillaumeDeWin** [replicate/cog#1191]
I get this error when I call the Meronym API (hosted on a remote server) with a file of more than 100mb. Is there an env var I could assign to a greater value ?

**Comment by mattt** [comment]
Hi, @GuillaumeDeWin. Can you provide more details about what model you're trying to run and how you're running it? Specifically:

- A link to the model on Replicate, if available
- A link to the source repo for the model, if available
- The command you're running
- The output of running that command

**Comment by GuillaumeDeWin** [comment]
Hey @mattt thank you for reaching out !

I was running this model :
https://replicate.com/meronym/speaker-transcription
https://github.com/meronym/speaker-diarization

The issue ended up having deployed an instance too small to run the model. It's now working fine on a g4dn.2xlarge instance on AWS
