### ISSUE TITLE
Possible to run on remote docker host?

### ISSUE THREAD

**Issue by whydna** [replicate/cog#1200]
Is it possible to run cog predict if the docker host is on a remote server?

**Comment by mattt** [comment]
Hi, @whydna. Yes, you can run `cog predict` on a remote Docker host. Here's an example from [Stable Diffusion on Replicate](https://replicate.com/stability-ai/stable-diffusion):

```console
$ cog predict r8.im/stability-ai/stable-diffusion@sha256:ac732df83cea7fff18b8472768c88ad041fa750ff7682a21affe81863cbe77e4 \
  -i prompt="an astronaut riding a horse on mars, hd, dramatic lighting"
```

This should work on any Docker container registry, local or remote.

**Comment by whydna** [comment]
Hi Matt,

Thanks for the reply.

```
docker context create my-server docker host=123.456.78.9
docker use my-server

cog predict -i prompt="an astronaut riding a horse on mars"
``

This just times out
