### ISSUE TITLE
How does cog.Path work? 

### ISSUE THREAD

**Issue by kenhuangsy** [replicate/cog#1219]
Hey guys, I'm wondering how cog.Path work? Currently, I just have this code to load the image, but it accepts strings:
```
def load_image(image_file: str):
    if image_file.startswith('http') or image_file.startswith('https'):
        response = requests.get(image_file)
        image = Image.open(BytesIO(response.content)).convert('RGB')
    else:
        image = Image.open(image_file).convert('RGB')
    return image
```
Is there a way I can modify this code so that it works with cog.Path or should I use cog.File here? 

Ultimately, I'm trying to pass an image in the form of numpy array into the model, but I'm not sure how. Can I create my own datatype for the API or is that not allowed?

**Comment by hongchaodeng** [comment]
`cog.Path` is a class that extends the `pathlib.PosixPath` class. It defines a custom validator for the `pathlib.Path` type that can be used to validate and convert input values to `pathlib.Path` objects.

You can check the code here: https://github.com/replicate/cog/blob/cb5b9bc9d0424e250af78e9b6d47438372d45afe/python/cog/types.py#L75
