### ISSUE TITLE
Is it necessary to keep the cloud instance once I have uploaded to replicate?

### ISSUE THREAD

**Issue by kenhuangsy** [replicate/cog#1220]
Hey guys, I'm wondering once I have pushed my model to replicate, do I still have to keep my cloud instance running? I'm asking because I noticed that replicate has its own pricing https://replicate.com/pricing. Thanks in advance!

**Comment by mattt** [comment]
Hi @kenhuangsy. Yes — once you've pushed your model to Replicate, you can terminate your cloud GPU session.
