### ISSUE TITLE
Jupyter Notebook Integration

### ISSUE THREAD

**Issue by burkaygur** [replicate/cog#123]
Would love to see some kind of notebook integration. Can we expose the environment built in Docker as a Jupyter Notebook kernel possibly?

**Comment by bfirsh** [comment]
For sure. As a basic integration, you should able to run jupyter notebooks inside the Cog environment. This should just work:

```
cog run jupyter notebook
```

It's a bit clunky unless we do something clever. This is sort of what you need to do right now:

```
cog run -p 8080 jupyter notebook --ip 0.0.0.0 --no-browser --port=8080 --allow-root
```

(We don't actually support `-p` yet.)

**Comment by bfirsh** [comment]
Superseded by #488
