### ISSUE TITLE
Cog build fails on Ubuntu

### ISSUE THREAD

**Issue by AbdullahMakhdoom** [replicate/cog#1235]
Ubuntu : 22.04.2 LTS
Docker : 20.10.21, build 20.10.21-0ubuntu1~22.04.3
Cog : cog version 0.8.3 (built 2023-07-27T21:48:28Z)
GPU : false

Failed to build getting-started python environment with `cog init`.

Output is :-
```
abdullah@abdullah-HP-EliteBook-840-G4:~/Desktop/Github/cog-getting-started$ cog run python
Building Docker image from environment in cog.yaml...
unknown flag: --file
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default
                           "/home/abdullah/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level
                           ("debug"|"info"|"warn"|"error"|"fatal")
                           (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/home/abdullah/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "/home/abdullah/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/home/abdullah/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

ⅹ Failed to build Docker image: exit status 125
```

**Comment by huyyxy** [comment]
I encountered the same problem. who can help us?

**Comment by huyyxy** [comment]
(sd) sd@ecs-cog:~/replicate$ uname -a
Linux ecs-cog 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(sd) sd@ecs-cog:~/replicate$ cog --version
cog version 0.8.3 (built 2023-07-27T21:48:28Z)
(sd) sd@ecs-cog:~/replicate$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2

`
(sd) sd@ecs-cog:~/replicate$ cog build
⚠ Cog doesn't know if CUDA 11.6.2 is compatible with PyTorch 2.0.1. This might cause CUDA problems.
Building Docker image from environment in cog.yaml as cog-sdxl...
unknown flag: --file
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default
                           "/home/sd/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level
                           ("debug"|"info"|"warn"|"error"|"fatal")
                           (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/home/sd/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "/home/sd/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/home/sd/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

ⅹ Failed to build Docker image: exit status 125
`

**Comment by mattt** [comment]
Thanks for sharing this, @AbdullahMakhdoom @huyyxy. I'm unable to reproduce this locally, either on macOS or running ubuntu jammy emulated with OrbStack.

```
$ uname -a
Linux ubuntu 6.4.7-orbstack-00058-g16f30394f179 #1 SMP Sun Jul 30 06:52:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ cog run python
Running 'python' in Docker with the current directory mounted as a volume...
Python 3.11.4 (main, Jul 28 2023, 05:12:06) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Are you able to run previous versions of Cog successfully, like [v0.7.2](https://github.com/replicate/cog/releases/tag/v0.7.2)? I'm wondering if this is a new regression.

**Comment by AbdullahMakhdoom** [comment]
Hi @mattt thank you for your response.
So I downloaded release [v0.7.2](https://github.com/replicate/cog/releases/tag/v0.7.2) and the `cog run python` command was successfully able to start python interpreter.

**Comment by EBazarov** [comment]
Had the same issue on Ubuntu 20.04.04 LTS with Docker version 24.0.2.
With cog version 0.8.6 (built 2023-08-07T21:51:56Z) it provides exactly the same error message as the author of this issue had.
```
Building Docker image from environment in cog.yaml...
unknown flag: --file
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND
```

I'm not sure, but looks like cog pass arguments to `docker` command, instead of `docker build`.

**Comment by pbarker** [comment]
Also seeing this on MacOS 13.4.1 with `cog version 0.8.6 (built 2023-08-07T21:51:56Z)`

**Comment by pbarker** [comment]
confirmed switching to v0.7.2 works

**Comment by AWaselnuk** [comment]
I just hit the same problem on:

MacOS Monterey v12.6 Intel Core i9
Docker v24.0.5
cog v0.8.6

The problem ended up being my docker installation.

I believe it's because I installed docker via `homebrew`. The latest versions of docker engine put the `buildx` tool into a separate package. Installing docker-buildx via `homebrew` didn't help. Finally I completely uninstalled from homebrew and reinstalled via their downloadable Docker Desktop product which I believe packages all that stuff together for you.

Once I reinstalled Docker I was able to dry run `cog run echo hello` successfully using the latest build v0.8.6

**Comment by AWaselnuk** [comment]
Here is the command to grab a specific older version for others who need that. Example for v0.7.2

`sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/download/v0.7.2/cog_$(uname -s)_$(uname -m)"`

**Comment by dsingal0** [comment]
Please update cog and install the buildx plugin for docker to resolve this.

**Comment by smartartdev** [comment]
> Had the same issue on Ubuntu 20.04.04 LTS with Docker version 24.0.2. With cog version 0.8.6 (built 2023-08-07T21:51:56Z) it provides exactly the same error message as the author of this issue had.
> 
> ```
> Building Docker image from environment in cog.yaml...
> unknown flag: --file
> See 'docker --help'.
> 
> Usage:  docker [OPTIONS] COMMAND
> ```
> 
> I'm not sure, but looks like cog pass arguments to `docker` command, instead of `docker build`.
> 
> UPDATE: Tried with v0.7.2 and had another error message
> 
> ```
> Building Docker image from environment in cog.yaml...
> ERROR: BuildKit is enabled but the buildx component is missing or broken.
>        Install the buildx component to build images with BuildKit:
>        https://docs.docker.com/go/buildx/
> ⅹ Failed to build Docker image: exit status 1
> ```
> 
> Will try to install buildx, maybe that was an issue

have you solve this problem?

**Comment by AlexanderKozhevin** [comment]
problem still exist on ubuntu 😔

**Comment by harrisMLEng** [comment]
Problem still exists on ubuntu

**Comment by ramonpzg** [comment]
> Please update cog and install the buildx plugin for docker to resolve this.

I had the same issue in Arch but this fixed the issue for me. Thanks @dsingal0 :+1:
