### ISSUE TITLE
Error when using --separate-weights

### ISSUE THREAD

**Issue by Darcheeni** [replicate/cog#1270]
Get the following error when trying to use the separate weights flag on my first build. Running on an M1 MacBook.

Building Docker image from environment in cog.yaml as r8.im/umarramzan/packet-manager...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102d6091c]

goroutine 1 [running]:
github.com/replicate/cog/pkg/weights.(*Manifest).Equal(...)
        /private/tmp/cog-20230727-4732-1tv3cfa/cog-0.8.3/pkg/weights/manifest.go:66
github.com/replicate/cog/pkg/image.Build(0x1400022e680, {0x1400002c044, 0x35}, {0x16d4c7531, 0x1f}, {0x103281b20, 0x0, 0x0}, 0x0?, 0x1, ...)
        /private/tmp/cog-20230727-4732-1tv3cfa/cog-0.8.3/pkg/image/build.go:54 +0x29c
github.com/replicate/cog/pkg/cli.push(0x1400025d200?, {0x140002295a0, 0x1, 0x2?})
        /private/tmp/cog-20230727-4732-1tv3cfa/cog-0.8.3/pkg/cli/push.go:49 +0xc0
github.com/spf13/cobra.(*Command).execute(0x1400025d200, {0x14000229580, 0x2, 0x2})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400025c000)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(0x60?)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()

**Comment by catsby** [comment]
Hello 👋 - I think this was a hidden bug/issue in v0.8.3 version that it appears you're using, based on the output. I believe this bug was patched in https://github.com/replicate/cog/pull/1239 which was released in version v0.8.5 : 

- https://github.com/replicate/cog/releases/tag/v0.8.5

Could you try updating your version of `cog` to at least v0.8.5 and see if the problem remains? 

Cheers!

**Comment by Darcheeni** [comment]
Yes that fixed it. Thank you!

**Comment by catsby** [comment]
Great to hear! Cheers
