### ISSUE TITLE
Specify gpu_id for cog predict jobs

### ISSUE THREAD

**Issue by aiXander** [replicate/cog#1283]
It would be awesome if there was a simple flag to set the gpu_id to be used for cog (on a machine with multiple gpu's)
eg
`cog predict -i prompt="text input" -i cuda_id=0`

setting `export CUDA_VISIBLE_DEVICES=1` first in the terminal does not work as docker ignores it.

There's this way to do it, but it's so cumbersome...
![image](https://github.com/replicate/cog/assets/24993604/8c26fa55-cd72-473c-821c-d62c8bf85d2d)

**Comment by bfirsh** [comment]
Agreed: https://github.com/replicate/cog/pull/1334

**Comment by bfirsh** [comment]
@aiXander This is now in a prerelease version! https://github.com/replicate/cog/releases/tag/v0.9.0-beta7
