### ISSUE TITLE
/dev/shm is 64MB in replicate.com but it is 8GB when run with predict from cog

### ISSUE THREAD

**Issue by nelsonjchen** [replicate/cog#1293]
`mount | grep /dev/shm` on replicate.com:

`shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)`

`mount | grep /dev/shm` when running with `cog predict`:

`shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=8388608k)`

https://github.com/replicate/cog/blob/12b79d553f3885aab6f140ddc9c7099a2a0ffd40/pkg/docker/run.go#L52-L59

references https://github.com/pytorch/pytorch/issues/2244, which seems to reference some PyTorch functionality that uses /dev/shm and a lot of it.

I can't say I know what models are affected by this issue since there have been so many models without this issue and the referenced PyTorch issue might be more of a developer issue. Either way, it'll probably be better for either replicate.com to specify 8GB of `/dev/shm` when containers are spun up to match cog or the other way around to keep surprises low.

**Comment by nelsonjchen** [comment]
For what it's worth, I would love to have /dev/shm be 8GB or at least 1GB for my use. Having access to a large SHM for my jobs would greatly simplify things.

**Comment by yorickvP** [comment]
Should be resolved now. Please re-open if it isn't.

**Comment by nelsonjchen** [comment]
Only issue is documentation:

`tmpfs on /dev/shm type tmpfs (rw,relatime,size=6144000k)`

6GB, great! Hopefully cog now matches 6GB as well. I can't check at the moment but if not, yeah, this issue can be reopened. 😁
