### ISSUE TITLE
why  can not play "mp4v" video on replicate?

### ISSUE THREAD

**Issue by geoxpert0001** [replicate/cog#1301]
my model output is xxx.mp4, which is mp4v codec format.
why i can not see video and play on replicate?
![image](https://github.com/replicate/cog/assets/141697815/f7d8a622-0fb5-4682-ba0e-7000e9f3ee3b)

but i download it from replicate, it can show video result.

can you fix it on replicate that can support mp4v codec format.
thanks.

**Comment by mattt** [comment]
Hi @geoxpert0001. I found your prediction, and the video loaded without a problem for me, so this may be a problem with your browser settings.

<img width="1127" alt="Screenshot 2023-09-12 at 04 53 35" src="https://github.com/replicate/cog/assets/7659/f7c1fd7a-c929-4ec8-be93-8bdb432bb392">

In any case, this doesn't appear to be a problem with Cog specifically, so I'm going to close this issue. If you have any problems with Replicate's website, please reach out on [Discord](https://discord.gg/replicate). Thanks!

**Comment by geoxpert0001** [comment]
@mattt 
i use chrome, brave and edge browser(also change computers to test), the video result did not show any more.

Can you change another account to test?
Because my friend also encountered the same problem.
Our account setting is without credit card.
thanks
