### ISSUE TITLE
Every time I make a small code change, cog pushes my safetensor files all over again

### ISSUE THREAD

**Issue by clearly-outsane** [replicate/cog#1305]
Is there a way to tell cog to ignore large files that haven't changed?

**Comment by mattt** [comment]
Hi @clearly-outsane. Yes, you should be able to speed up subsequent builds by passing the `--separate-weights` flag to `cog build`:

> Model repos often contain large data files, like weights and checkpoints. If you put these files in their own subdirectory and run `cog build` with the `--separate-weights` flag, Cog will copy these files into a separate Docker layer, which reduces the time needed to rebuild after making changes to code.
