### ISSUE TITLE
Which Python versions are not supported by Cog?

### ISSUE THREAD

**Issue by geoxpert0001** [replicate/cog#1328]
![image](https://github.com/replicate/cog/assets/141697815/ff1b61fc-4ce3-4233-b435-b01a34ad8e85)

i just saw cog.yaml reference, and i have a question.
so if i use python version 3.8 before, e.g. python=3.7 python=3.5 ....
is it working on cog?

thanks.

**Comment by mattt** [comment]
Hi @geoxpert0001. Cog currently supports Python >= 3.7

https://github.com/replicate/cog/blob/2e42a3f7edacf7d53e522f1f9611795eda142991/pyproject.toml#L13
