### ISSUE TITLE
Which Cuda versions are not supported by Cog?

### ISSUE THREAD

**Issue by geoxpert0001** [replicate/cog#1330]
Does Cog support all CUDA versions or not?
I want to know if older CUDA versions are compatible and functional.

**Comment by catsby** [comment]
Hi 👋 there's a generated file [pkg/config/cuda_base_images.json](https://github.com/replicate/cog/blob/2e42a3f7edacf7d53e522f1f9611795eda142991/pkg/config/cuda_base_images.json) which appears to be a list of CUDA base images and versions included. I can't say if it's definitive or up to date, but reading it implies to me the following versions are supported: 

```
12.1.1
12.0.1
12.0.0
11.8.0
11.7.1
11.6.2
11.5.2
11.4.3
11.3.1
11.2.2
11.1.1
11.0.3
```

I could be wrong though... it looks like this file is used for validating `cog.yaml` files(?). Hopefully this helps, but I realize it's not definitive.

**Comment by mattt** [comment]
Thanks, @catsby! That's exactly right. Cog uses this generated list of CUDA base images to resolve PyTorch and TensorFlow packages to compatible versions. 

For some historical context, Nvidia recently removed some older CUDA image tags from Docker Hub, which resulted in Cog resolving to images that no longer existed (#1162).
