### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by selintunr** [replicate/cog#1339]
Hi @mattt , thank you for the good work. How can I keep the container running after a prediction?

**Comment by mattt** [comment]
Hi @selintunr. `cog predict` starts up a container, runs the model once, and shuts down. To keep it running, you can do `cog build` to build the image, `docker run` to run the container, and `curl` to send predictions to the running container.

From the README:

> ```
> $ cog build -t my-colorization-model
> --> Building Docker image...
> --> Built my-colorization-model:latest
> 
> $ docker run -d -p 5000:5000 --gpus all my-colorization-model
> 
> $ curl http://localhost:5000/predictions -X POST \
>     -H 'Content-Type: application/json' \
>     -d '{"input": {"image": "https://.../input.jpg"}}'
> ```
