### ISSUE TITLE
Is it possible to specify which .dockerignore file to use?

### ISSUE THREAD

**Issue by ynie** [replicate/cog#1427]
Hello, we would like to specify which dockerignore file to use. Let us know if there's a way to do it. Thank you so much!

**Comment by technillogue** [comment]
you can symlink .dockerignore to point to the desired dockerignore before running cog. depending on what you're doing, a makefile can be beneficial. for a somewhat messy example of this, you can check out https://github.com/replicate/cog-llama-template/blob/main/Makefile#L95-L96
