### ISSUE TITLE
 do we really need embed golang? 

### ISSUE THREAD

**Issue by emptyworld0** [replicate/cog#1457]
I read code recently.

Do we really need  //go:embed embed/cog.whl in file generator.go ? 

I think we can use docker command COPY instead.

I'm wondering why design like this.

**Comment by mattt** [comment]
@emptyworld0 Using embed here allows Cog to be distributed as a self-contained binary. Otherwise, you'd have an external dependency on the Cog Python wheel being installed on the system.

**Comment by emptyworld0** [comment]
> @emptyworld0 Using embed here allows Cog to be distributed as a self-contained binary. Otherwise, you'd have an external dependency on the Cog Python wheel being installed on the system.

Thanks mat. I get cog from compile the source code in local machine.  Never thought the distribute situation.
