### ISSUE TITLE
Automatically publish Python package on PyPi on release

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#146]
Currently there is a package that has been manually released, but it is not automated.

https://pypi.org/project/cog/

We should also set some expectation around what this package is. Just the Python package doesn't actually do very much.

**Comment by zeke** [comment]
Here's a hack that I'm using to build the `cog` package locally so it can be imported into automated tests: https://github.com/zeke/cog-kitchen-sink/pull/2

**Comment by bfirsh** [comment]
https://pypi.org/project/cog/
