### ISSUE TITLE
Ctrl-C doesn't quit prediction server when running container directly

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#150]
When I run `docker run model` and hit Ctrl-C, it doesn't quit the prediction server.

<img width="790" alt="Screen Shot 2021-07-15 at 11 32 25" src="https://user-images.githubusercontent.com/40906/125839350-a8005300-c0ff-45f6-a9fc-f25b7ca98af1.png">

**Comment by zeke** [comment]
Is this something that can be fixed in Cog?

Can this be "fixed" with documentation about including the `--init` flag when running docker commands?

**Comment by bfirsh** [comment]
Either I think! I think this could be something that could be fixed in Cog (and may be fixed now we switched to FastAPI?).

**Comment by zeke** [comment]
Yep, it works! Just ran this (without `--init`) and was able to `ctrl-C` to exit:

```
docker run -p 5000:5000 --platform=linux/amd64 r8.im/zeke/haiku-progressive-image
```

<img width="1440" alt="Screen Shot 2022-03-14 at 4 24 39 PM" src="https://user-images.githubusercontent.com/2289/158276860-0e1f6246-61e6-4030-8fab-11648f14c1c8.png">

**Comment by bfirsh** [comment]
I love it when bugs fix themselves. Good bug.
