### ISSUE TITLE
invalid png data when running on multiple gpus

### ISSUE THREAD

**Issue by uvilop** [replicate/cog#1513]
i tried running multiple diffuser processes in parallel on a multi-gpu host:

cd /src/
export PORT=5000
export CUDA_VISIBLE_DEVICES=0
python -m cog.server.http &
export PORT=5001
export CUDA_VISIBLE_DEVICES=1
python -m cog.server.http &
...

in principle this works, but about 10% of the resulting png image data ist corrupt (base64 decodes, but the image has crc error).
when running only 1 process, everything works fine.

**Comment by yorickvP** [comment]
Interesting! It's probably related to using the same input/output file paths. Try instead to spawn multiple docker containers with a different `--gpus` flag.
