### ISSUE TITLE
checksum mismatch for 0.9.4 release

### ISSUE THREAD

**Issue by stefanb** [replicate/cog#1518]
👋 it looks like 0.9.4 release got re-created, raise this issue to confirm it. Thanks!

relates to 
* https://github.com/Homebrew/homebrew-core/pull/162013

This affects
* https://github.com/Homebrew/homebrew-core/pull/161976
* https://github.com/Homebrew/homebrew-core/pull/157782

cc: @mattt, @zeke: can you confirm that retagging was done on 0.9.4 ?

**Comment by zeke** [comment]
I'm not sure. cc @technillogue

**Comment by chenrui333** [comment]
Another way to get away with this is maybe publishing the source tarball into pypi.

<img width="1211" alt="image" src="https://github.com/replicate/cog/assets/1580956/8fb50189-05ec-4616-9ec9-5b16fbc496fd">
