### ISSUE TITLE
name unknown: The model https://replicate.com/username/modelname does not exist

### ISSUE THREAD

**Issue by sepehr** [replicate/cog#1519]
Hi there,

Even though I can run a successful `cog login`, at the time I'm trying to push the model, I get this error no matter what model. The model is created on replicate.com and exists.

This was not the case few days ago. I started experiencing this after I created a new account and ran `cog login` with the token from that account. 

Pushing models from neither works now. Login is according to the CLI message, successful. 

Would appreciate your help.

**Comment by mattt** [comment]
Hi, @sepehr. I'm sorry this stopped working for you. You mentioned that you created a new account. Are pushes failing for that account, or for the one associated with the GitHub account you commented from? And can you share the name of a model you tried to push with that account? (That would help me find a trace in our system to see what happened)

**Comment by sepehr** [comment]
Hi @mattt, thanks for the quick follow-up and your support. 

Pushes were failing for both accounts. I have since isolated & addressed the issue by looking at the way [login](https://github.com/replicate/cog/blob/main/pkg/docker/login.go) works. I have deleted the entries for r8.im from my machine's secretstore, and did another `cog login`, seeing that the push afterwards went through :tada: 

To see whether this is cog-related, below is my docker config and os spec. 

```json
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "secretservice",
	"currentContext": "desktop-linux"
}
```

Linux hostname 6.5.11-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

**Comment by mattt** [comment]
@sepehr Thanks for digging into this. I'm glad to hear that you found a resolution.

I'll have to take another look at `cog login` to see if it's handling multiple login correctly. Maybe we should add a `cog logout` command that deletes r8.im entries in the secret store as you did manually?

**Comment by sepehr** [comment]
I think that's a very good idea, @mattt :+1: Honestly, I tried a `cog logout` first, but realized that's not a thing yet.

**Comment by robinsonkwame** [comment]
Seeing this same issue, here are my steps,
* Created a private model (`robinsonkwame/nerfstudio-cli`) on replicate.com, 
* To `cog.yaml` added `image: "r8.im/robinsonkwame/nerfstudio-cli"`
* `cog login`, authenticated, recieved `You've successfully authenticated as robinsonkwame! You can now use the 'r8.im' registry.`
* ran `sudo cog push r8.im/robinsonkwame/nerfstudio-cli`
```
Building Docker image from environment in cog.yaml as r8.im/robinsonkwame/nerfstudio-cli
...
Validating model schema...
Adding labels to image...

Pushing image 'r8.im/robinsonkwame/nerfstudio-cli'...
Using default tag: latest
The push refers to repository [r8.im/robinsonkwame/nerfstudio-cli]
...
name unknown: The model https://replicate.com/robinsonkwame/nerfstudio-cli does not exist
ⅹ exit status 1
```
but `https://replicate.com/robinsonkwame/nerfstudio-cli` returns successfully in the browser.

**Comment by robot007** [comment]
@sepehr Thanks for your hint. 
I had the same problem: The Cog push did not work for me. I see the following error: 

name unknown; The model [my model] does not exist

I am very sure the model exists and I pushed to it once. This bug exists for **cog version 0.9.4 (built 2024-01-24T22:16:49Z)** My desktop is Ubuntu 22.04.3 LTS.

**The patch**: delete ~/.docker/config.json and use Cog login., then Cog push It is a temporary solution.

@mattt if you are working for Replicate, could you please fix the problem in Cog. Thanks.

**Comment by leonmak** [comment]
not using sudo `sudo cog login` was the issue for me

**Comment by immex-tech** [comment]
yes, it needs 'sudo cog login'. Till the issue is fixed, for now, we might as well update "push your model' section in https://replicate.com/docs/guides/push-a-model

**Comment by aelyoussfi** [comment]
I had same issue, using sudo with cog login worked for me.
