### ISSUE TITLE
how to do a slider view in replicate

### ISSUE THREAD

**Issue by tzktz** [replicate/cog#1533]
bro @mattt  , @zeke , @anotherjesse 

how to set the slider view for an input and output image in replicate? 
here is model https://replicate.com/codeplugtech/object_remover

**Comment by zeke** [comment]
Hey @tzktz. It's not configured in Cog. It's a setting we can manually enable on the Replicate website. This feature doesn't currently work for models that take multiple image inputs, but I'm looking into supporting that now.

**Comment by tzktz** [comment]
thx for ur information @zeke bro...!!!
