### ISSUE TITLE
Cog Push not working

### ISSUE THREAD

**Issue by iftachAvital** [replicate/cog#1534]
After authenticating with cog login getting unauthorized: You are not logged in to Replicate. Run 'cog login' and try again.
I have try with or without sudo. Any ideas?

You've successfully authenticated as iftachavital! You can now use the 'r8.im' registry.
(.venv) iftach@iftach-System-Product-Name:~/PycharmProjects/replicate-whisper$ sudo cog push r8.im/iftachavital/whisper-large-v3
⚠ Cog doesn't know if CUDA 12.1 is compatible with PyTorch 2.2.0. This might cause CUDA problems.
Building Docker image from environment in cog.yaml as r8.im/iftachavital/whisper-large-v3...
[+] Building 1.3s (21/21) FINISHED                                                                                                            docker:default
 => [internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 357B                                                                                                                       0.0s
 => [internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 2.08kB                                                                                                                  0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4                                                                                            0.5s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                       0.0s
 => [internal] load metadata for docker.io/library/python:3.11                                                                                          0.5s
 => [internal] load metadata for docker.io/nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04                                                                  0.5s
 => [deps 1/5] FROM docker.io/library/python:3.11@sha256:4f7a334f9b8941fc7779e17541eaa0fd6043bdb63de1f5b0ee634e7991706e63                               0.0s
 => [internal] load build context                                                                                                                       0.0s
 => => transferring context: 91.35kB                                                                                                                    0.0s
 => [stage-1 1/7] FROM docker.io/nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04@sha256:21196d81f56b48dbee70494d5f10322e1a77cc47ffe202a3bf68eab81533c20f    0.0s
 => CACHED [stage-1 2/7] RUN --mount=type=cache,target=/var/cache/apt set -eux; apt-get update -qq; apt-get install -qqy --no-install-recommends curl;  0.0s
 => CACHED [stage-1 3/7] RUN --mount=type=cache,target=/var/cache/apt apt-get update -qq && apt-get install -qqy --no-install-recommends  make  build-  0.0s
 => CACHED [stage-1 4/7] RUN curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash &&  git clone htt  0.0s
 => CACHED [deps 2/5] COPY .cog/tmp/build3337785366/cog-0.0.1.dev-py3-none-any.whl /tmp/cog-0.0.1.dev-py3-none-any.whl                                  0.0s
 => CACHED [deps 3/5] RUN --mount=type=cache,target=/root/.cache/pip pip install -t /dep /tmp/cog-0.0.1.dev-py3-none-any.whl                            0.0s
 => CACHED [deps 4/5] COPY .cog/tmp/build3337785366/requirements.txt /tmp/requirements.txt                                                              0.0s
 => CACHED [deps 5/5] RUN --mount=type=cache,target=/root/.cache/pip pip install -t /dep -r /tmp/requirements.txt                                       0.0s
 => CACHED [stage-1 5/7] RUN --mount=type=bind,from=deps,source=/dep,target=/dep cp -rf /dep/* $(pyenv prefix)/lib/python*/site-packages || true        0.0s
 => CACHED [stage-1 6/7] WORKDIR /src                                                                                                                   0.0s
 => [stage-1 7/7] COPY . /src                                                                                                                           0.0s
 => preparing layers for inline cache                                                                                                                   0.0s
 => exporting to image                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                 0.0s
 => => writing image sha256:01d557f6907a1fe4df0c5f659e3867c522dfef9d3482314d4f290f556bd267fe                                                            0.0s
 => => naming to r8.im/iftachavital/whisper-large-v3                                                                                                    0.0s
Validating model schema...
Adding labels to image...

Pushing image 'r8.im/iftachavital/whisper-large-v3'...
Using default tag: latest
The push refers to repository [r8.im/iftachavital/whisper-large-v3]
84d526fd94c8: Preparing 
ba9326c99275: Preparing 
90f8ba00d1c8: Preparing 
f497f6e1e628: Preparing 
80df68a98384: Preparing 
94fb9273eb30: Waiting 
0f7c883f1a4f: Waiting 
7aee75a70a2f: Waiting 
24e1e08aaa60: Waiting 
3416903c2cc4: Waiting 
83687aeafbbf: Waiting 
83ecbf43a888: Waiting 
b15b1df4adac: Waiting 
bea30ebbe843: Waiting 
8afeff4e91d7: Waiting 
6ec2b659c9ab: Waiting 
566cd9dd29d6: Waiting 
256d88da4185: Waiting 
unauthorized: You are not logged in to Replicate. Run 'cog login' and try again.
ⅹ exit status 1

**Comment by tzktz** [comment]
Run ```cog login```
Enter your authentication secret code then try push

**Comment by lucataco** [comment]
Make sure you created the Replicate model "whisper-large-v3" under your user `iftachavital` before attempting a cog push
