### ISSUE TITLE
do you support zk proof?

### ISSUE THREAD

**Issue by wade-liwei** [replicate/cog#1568]
https://github.com/zkonduit/ezkl

**Comment by mattt** [comment]
Hi @wade-liwei. Sorry for not responding sooner.

I'm not aware of any models built using ezkl with Cog, but I don't see any reason why you couldn't implement this yourself.

Check out the docs in this project and on replicate.com to get started. If you have any questions, you can try asking on our [Discord](https://discord.com/invite/replicate).
