### ISSUE TITLE
Optional Shutdown Event

### ISSUE THREAD

**Issue by bakermanbrian** [replicate/cog#1590]
It would be great if a Cog also had shutdown event in the BasePredictor to be able to handle the full setup, predict, and shutdown lifecycle.

**Comment by mattt** [comment]
@bakermanbrian Thanks for sharing your suggestion. Do you have a specific use case in mind for a shutdown event?

**Comment by mattt** [comment]
@bakermanbrian Ah, thanks for clarifying. This sounds like a task best solved at the orchestration layer. For example, if running a Cog container in a Kubernetes cluster, you could use [container events](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_events/) or log statements to determine when a pod starts and finishes. That way, you'll get consistent statistics even if Cog terminates unexpectedly, without executing the configured shutdown handler.
