### ISSUE TITLE
Replicate API taking more than 2 min on T4 GPU

### ISSUE THREAD

**Issue by Shivansh-yadav13** [replicate/cog#1594]
This is my cog file

```yaml
build:
  gpu: true
  python_version: "3.10"
  python_packages:
    - "diffusers"
    - "accelerate"
    - "peft"
    - "transformers"

predict: "predict.py:Predictor"
```

This is my `predict.py`

```py
import torch
import base64
from io import BytesIO
from PIL import Image
from cog import BasePredictor, Input, Path
from diffusers import AutoPipelineForInpainting

class Predictor(BasePredictor):

  def setup(self):
    pipe = AutoPipelineForInpainting.from_pretrained('stabilityai/sdxl-turbo', torch_dtype=torch.float16, variant="fp16")
    pipe.to('cuda')
    pipe.load_lora_weights("./sdxl_turbo_lora.safetensors")
    self.pipe = pipe
  
  def predict(self, input_image_base64: str = Input(description="Input base64 string"), mask_base64: str = Input(description="Mask base64 string")) -> str:

    base64_decoded = base64.b64decode(input_image_base64)
    input_image = Image.open(BytesIO(base64_decoded))

    base64_decoded = base64.b64decode(mask_base64)
    mask_image = Image.open(BytesIO(base64_decoded))
  
    output = self.pipe(
      prompt="remove wrinkles from the cloth, make shirt color black, don't operate on cloth folds, avoid changing cloth text or font prints",
      negative_prompt="wrinkled, low quality texture, degenerated texture, unintelligible text, overexposed, worst quality, low quality, jpeg artifacts, ugly, deformed, blurry, extra pockets, distorted hands",
      image=input_image,
      mask_image=mask_image,
      num_inference_steps=5,
      strength=0.5,
      guidance_scale=1
    ).images[0]
    
    buffered = BytesIO()
    output.save(buffered, format="JPEG")
    img_str = base64.b64encode(buffered.getvalue())

    return img_str
```

The above model is setup to run on T4 GPU, and on T4 GPU sdxl-turbo returns outputs in seconds. Even though the prediction logs states on avg 4 seconds, I'm getting output on my app after 2+ minutes.

![Screenshot 2024-03-25 161114](https://github.com/replicate/cog/assets/87603425/8c0befad-f690-4a1a-a1b7-6d7890da390a)

To reproduce this you can use the below repo it's readme

https://github.com/Team-Iron-The-Dress/replicate-cog-model/tree/main

This is my model

https://replicate.com/shivansh-yadav13/iron-the-dress/versions/33757df23f3c36414a02ae99701f1c2dd1d4c3eddd29b5ae04fa0ed145044441

**Comment by mattt** [comment]
Hi @Shivansh-yadav13. Sorry for not responding sooner.

That additional 2 minutes looks to be from the model being [cold](https://replicate.com/docs/how-does-replicate-work#cold-boots) and booting up. You can get more consistent performance with a [deployment](https://replicate.com/docs/guides/deploy-a-custom-model) of that model, which you can figure to always have an instance running.

That said, the official [SDXL model](https://replicate.com/stability-ai/sdxl) has enough public traffic to always be warm, so you might consider using that instead.
