### ISSUE TITLE
Validating model schema... ⅹ Model schema is invalid: invalid components: schema "Output": extra sibling fields: [title] ⅹ 

### ISSUE THREAD

**Issue by micos7** [replicate/cog#1603]
I get this error:
 `Validating model schema...
ⅹ Model schema is invalid: invalid components: schema "Output": extra sibling fields: [title]`

on cog push r8.im/...

The model is created,I am logged in with sudo, it works locally. I`m lost , help! Thanks.

**Comment by mattt** [comment]
Hi @micos7. Sorry for not responding sooner.

This should be fixed in the latest version of Cog (see #1579). Please give that a try and let me know if things still aren't working for you.
