### ISSUE TITLE
AttributeError: 'Predictor' object has no attribute 'image_processor'

### ISSUE THREAD

**Issue by zhangying-666** [replicate/cog#1607]
AttributeError: 'Predictor' object has no attribute 'image_processor'

**Comment by mattt** [comment]
Hi @zhangying-666. This sounds like an error in your model implementation. Does your code reference `self.image_processor` without setting that attribute?

**Comment by mattt** [comment]
Closing this for now. Happy to reopen if you can provide more details, @zhangying-666.
