### ISSUE TITLE
mps support

### ISSUE THREAD

**Issue by nischalj10** [replicate/cog#1632]
i checked the readme and issues but could not find anything. is mps backend supported in cog apart from cuda? or are there plans to support it?

**Comment by mattt** [comment]
Hi @nischalj10. No, MPS (Metal Performance Shaders) is not a supported backend in Cog. MPS support isn't currently on our roadmap, but I'm excited to see Linux ARM64 and [Torch](https://github.com/pytorch/pytorch/issues/77764) starting to support MPS.
