### ISSUE TITLE
build fail 

### ISSUE THREAD

**Issue by abrar-tericsoft** [replicate/cog#1650]
the version has been disabled because it consistently fails to complete setup

**Comment by technillogue** [comment]
you need to provide more information for us to help you

**Comment by mattt** [comment]
Hi @abrar-tericsoft. Sorry to hear that things aren't working for you. Could you please share a link to your model on Replicate that's failing setup?

**Comment by mattt** [comment]
Closing this for now. Happy to reopen if you can provide any more details, @abrar-tericsoft.
