### ISSUE TITLE
Infinite loops happening without logs

### ISSUE THREAD

**Issue by MaximeDde** [replicate/cog#1665]
Hello there ! I'm opening an issue here as I wasn't able to find a solution on the mode l've been using in itself, and I am not sure it's related to it...

The model I use is https://replicate.com/thomasmol/whisper-diarization
Working perfectly for several months, no issues with that. But recently, for a reason I cannot find, I find myself with predicts that go in infinite loops, without logs nor warnings, and obviously cost me quite a lot (sometimes looping for one or two hours before I notice it...).

I just had one with the prediction ID [0e120sfsasrgp0cffm4bvtnb5c](https://replicate.com/p/0e120sfsasrgp0cffm4bvtnb5c)
By any chance, could someone help me identify if there may be something wrong on the Cog side that creates this behavior ? 

Best regards,

**Comment by mattt** [comment]
Hi @MaximeDde. Sorry that you're having problems with this model. 

[thomasmol/whisper-diarization](https://replicate.com/thomasmol/whisper-diarization) is a community model by a Replicate user. I noticed that [several new versions](https://replicate.com/thomasmol/whisper-diarization/versions) were pushed in the last few months, so if your code was running the latest version, that could explain the changes you observed. If you pin to a specific version SHA, that should ensure consistent behavior.

It looks like the source code for the model is available [here](https://github.com/thomasmol/cog-whisper-diarization). So if you wanted to make any other changes, you could push your own version and use that instead.
