### ISSUE TITLE
Add support for UI For predict in container

### ISSUE THREAD

**Issue by yairyairyair** [replicate/cog#1686]
I would like some env vars or flag when building a cog container to bake in the UI, probably some gradio or streamlit or something similar to what have in replicate hosted containers.

Basically that when running the container will also have path like /ui that serves a ui that i can use to call predict on the container instead trying some Curl or stuff like that.

This feature seems super useful in my own opinion, would be happy to discuss if needed.

Thanks!

**Comment by yairyairyair** [comment]
I mean a UI not like openapi swagger, i mean ui that infers the predict types and renders correct element for it for example file type render to allow file uploads.

**Comment by mattt** [comment]
Hi @yairyairyair. Thanks for sharing your suggestion. There are a few projects that generate a UI for Cog models, including [grog](https://github.com/multimodalart/grog). But for now, we don't have any plans to build this into Cog directly.
