### ISSUE TITLE
Update environment variable docs

### ISSUE THREAD

**Issue by zeke** [replicate/cog#1701]
https://github.com/replicate/cog/pull/991 added documentation for all the environment variables used by Cog, but some of them are misdocumented or shouldn't be documented at all because they're not part of Cog's public API.

Here's a list of the vars in the list. Which ones __should__ be documented?

- [ ] `CGO_ENABLED`
- [x] `COG_NO_UPDATE_CHECK`
- [ ] `LOG_FORMAT`
- [ ] `COG_WEIGHTS`
- [ ] `HOSTNAME`
- [ ] `COG_MODEL_ID`
- [ ] `COG_MODEL_NAME`
- [ ] `COG_USERNAME`
- [ ] `COG_MODEL_VERSION`
- [ ] `COG_HARDWARE`
- [ ] `COG_DOCKER_IMAGE_URI`
- [ ] `COG_LOG_LEVEL`
- [ ] `PORT`
- [ ] `COG_THROTTLE_RESPONSE_INTERVAL`
- [ ] `WEBHOOK_AUTH_TOKEN`
- [ ] `OTEL_SERVICE_NAME`
- [ ] `NVIDIA_DRIVER_CAPABILITIES`

**Comment by zeke** [comment]
Thanks @technillogue for taking a first pass at checking off the keepers. @nickstenning can you weigh in too?

I'll follow up with a PR.

**Comment by kej-jay** [comment]
Hi, I was wondering about the environment documentation, as for some variables the documentation does not specify, which value they need to be set to. For some vars it states (i.e. CGO_ENABLED "can be set to either 0 or 1"), but for some its not as clear (i.e. KUBERNETES_SERVICE_HOST "can be set / unset")
Further, I think it would be great if the [env variable docs](https://cog.run/environment/) could feature an explanation of where the variables need to be set (build env or in the image itself), which I guess would also help #1627

**Comment by nickstenning** [comment]
I've just unticked every single one of these except `COG_NO_UPDATE_CHECK`.

The situation is confused here by the fact that some of these are respected by `cog` the CLI program, and some of them are for `cog` the Python application which runs inside the container. IMO we're not in a position to document _any_ of the env vars used by the program inside the container.

**Comment by technillogue** [comment]
I would imagine that people may want to set LOG_FORMAT, COG_WEIGHTS, COG_LOG_LEVEL, PORT, COG_THROTTLE_RESPONSE_INTERVAL if they're running locally

**Comment by nickstenning** [comment]
We don't provide a straightforward mechanism for people to set env vars inside the container with `cog run`, so we first of all need to work out how to explain the difference between cog the CLI tool and cog the Python HTTP server.

**Comment by mattt** [comment]
Thanks for clarifying, @nickstenning. I opened https://github.com/replicate/cog/issues/1701, which removes everything except `COG_NO_UPDATE_CHECK` (and rewrites that for clarity).

**Comment by zeke** [comment]
Thank you!
