### ISSUE TITLE
Support multi-stage Dockerfile

### ISSUE THREAD

**Issue by hadilq** [replicate/cog#1708]
Hey! This issue is raised due to lack of a clear answer to this question: is cog wrapping replicate.com API, or wrapping Dockerfile? It looks like "both" is the correct answer, but that would impose a lot of restrictions and problems, like what I have.

My problem is I need to have a platform agnostic Dockerfile, so I could use it for different service providers. It would be possible if cog would support [multi-stage](https://docs.docker.com/build/building/multi-stage/) and I could introduce additional stages before cog.server.http is running.

Feel free to correct me, but I searched and I couldn't find a way to solve it. If it's what you think too, consider this as an enhancement.

**Comment by mattt** [comment]
Hi @hadilq. Cog builds images by generating a Dockerfile. It doesn't interact with Replicate's APIs itself.

If you want to change anything about the build process, you can run `cog debug > Dockerfile` and then update that Dockerfile however you choose.
