### ISSUE TITLE
Use cog with IPv6

### ISSUE THREAD

**Issue by Xe** [replicate/cog#1735]
I'm trying to use cog in an IPv6 native network ([Fly.io private networking](https://fly.io/docs/networking/private-networking/)) and cog doesn't seem to listen over IPv6:

```
root@e7842609f2d408:/src# curl http://[::1]:5000/ready
curl: (7) Failed to connect to ::1 port 5000 after 0 ms: Couldn't connect to server
```

How do I make cog listen on IPv6 so I can debug cog services directly in my private network?

**Comment by mattt** [comment]
Hi @Xe. I think this might be as straightforward as changing the configured host in our FastAPI app from `0.0.0.0` to `::`. I made this change in https://github.com/replicate/cog/pull/1748. Could you please try this out and let me know if that works for your use case?

**Comment by mattt** [comment]
@Xe Cog [v0.9.10](https://github.com/replicate/cog/releases/tag/v0.9.10) adds support for a `--host` argument when running the HTTP server. Following the instructions on [this doc](https://github.com/replicate/cog/blob/main/docs/deploy.md#--host), you should be able to run Cog models on IPv6 hosts. Please let me know how this works for you 😄
