### ISSUE TITLE
Integration with eureka server

### ISSUE THREAD

**Issue by AndreaRacoon** [replicate/cog#1737]
Hello, 
I am using py-eureka-client library to make it so that my cog machine learning app can subscribe to an eureka server.

I want to autoscale the number of cog containers of the same cog app.
But in order to scale down properly (make the client disconnect first from the server and then shut it down) I need to be able to disconnect the from the server on shutdown.

Is there a way to do that inside the cog app when calling /shudown API?

What do you recommend?

Thanks

**Comment by mattt** [comment]
Hi @AndreaRacoon. I'm not familiar with Eureka or Spring Cloud, so can't offer any specific guidance there. If you need to make a specific change to Cog to support your use case, Cog is open-source, so you can always fork the repo, make any changes, and deploy that.
