### ISSUE TITLE
tls: failed to verify certificate: x509: certificate is valid for civitai.com, *.civitai.com, *.cloudflarestorage.com, *.discordapp.com, *.googleusercontent.com, not us-docker.pkg.dev

### ISSUE THREAD

**Issue by yapianwan** [replicate/cog#1753]
centos ，use cog push

**Comment by mattt** [comment]
Hi @yapianwan. This seems like a networking issue on your end. Are you attempting to run `cog push` through a VPN?

**Comment by yapianwan** [comment]
@mattt I did not use a VPN, but I set up Docker image acceleration when creating the image.set registry-mirrors

**Comment by mattt** [comment]
@yapianwan Does installing `ca-certificates` resolve your issue?

```console
apt-get install -y ca-certificates
```

**Comment by yapianwan** [comment]
@mattt Tried but the problem persists

**Comment by mattt** [comment]
@yapianwan It sounds like the Docker image acceleration you configured may be interfering with your system's TLS stack. So you might try disabling that.

From the information you've provided, I don't think this is a problem with Cog specifically, so I'm going to close this issue for now. If you can provide an example of `docker push` working for an image built by Cog but `cog push` not working, then I'd be very happy to reopen and take a look.
