### ISSUE TITLE
how to include env like example OPENAI_API_KEY in cog.yaml?

### ISSUE THREAD

**Issue by octadion** [replicate/cog#1805]
Currently, I'm trying to configure my project using Cog, specifically using cog.yaml for Docker builds. I need to include environment variables such as OPENAI_API_KEY in my configuration, but it seems that cog.yaml does not support direct declaration of environment variables (env property).

**Comment by mattt** [comment]
Hi @octadion. Storing credentials in Cog / Docker images isn't recommended, as they can be read by anyone with access to the image. Instead, you can use the [`Secret`](https://github.com/replicate/cog/blob/main/docs/python.md#secret) input type to pass credentials to the model at runtime. 

If you're calling the OpenAI API at build time, you can [mount a secret](https://github.com/replicate/cog/blob/main/docs/private-package-registry.md) and access that file in a custom `run` step. But I suspect that's not your intended purpose.
