### ISSUE TITLE
cog fails to use custom image

### ISSUE THREAD

**Issue by fewjative** [replicate/cog#1814]
I'm trying to use this image:
nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04

I've put this in my cog.yaml
image: docker.io/nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04

However, cog is not picking up the new image and instead fallsback? to a base image without showing any error to the user. Here is the output when I run predict:

Building Docker image from environment in cog.yaml...
⚠ Stripping patch version from Python version 3.10.6 to 3.10
[+] Building 1.6s (13/13) FINISHED                                                                                                    docker:default
 => [internal] load build definition from Dockerfile                                                                                            0.0s
 => => transferring dockerfile: 515B                                                                                                            0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1.4                                                                     0.8s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc               0.0s
 => [internal] load .dockerignore                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                 0.0s
 **=> [internal] load metadata for r8.im/cog-base:cuda11.8-python3.10**                                                                             0.6s
 => [stage-0 1/5] FROM r8.im/cog-base:cuda11.8-python3.10@sha256:6e2e6a0e4539b9dae698489def51a84e1aca3edab7b47eb8a14e3186cac7b60f 

Expectation: I can specify custom images
Actual: Specifying custom image doesn't do anything and it fallsback to the bolded base image

**Comment by mattt** [comment]
Hi @fewjative. Thanks for reporting, and sorry for any inconvenience there.

We recently introduced a change https://github.com/replicate/cog/pull/1778 to make use of Cog base images default, and that appears to have caused a regression in how explicit `image` values are interpreted. Can you try re-running with the option `--cog-use-base-image=false`?

**Comment by mattt** [comment]
Hi @fewjative. The [`image` field in `cog.yaml`](https://cog.run/yaml/#image) has to do with the name given to the resulting image, not the base image used.

We don't currently support specifying a custom base image. You can run `cog debug` to generate a Dockerfile and swap out the base image, but if you're deploying to Replicate, I'd advise against doing that if possible, as it won't be optimized for our infrastructure and isn't guaranteed to boot correctly.

Instead, you can install any additional system dependencies by listing them in `system_packages` or adding any custom configuration as `run` steps.

**Comment by fewjative** [comment]
Ah I see. I think I would need to use a custom image in my case as from my own experience with deploying to replicate, the current base images used don't provide GPU acceleration. They'll use the GPU for ML tasks via cuda but if you want to do something like run OpenGL, then the current Replicate base image will fallback to software rendering. Closing but if you know how to otherwise get GPU accel working, please let me know!

**Comment by mattt** [comment]
@fewjative I haven't tried this myself, but I don't see any reason why you couldn't deploy a model to Replicate that uses the GPU to do accelerated rendering with OpenGL. [This article from NVIDIA](https://developer.nvidia.com/blog/linking-opengl-server-side-rendering) is old and maybe out of date, but mentions using [EGL](https://docs.nvidia.com/drive/drive_os_5.1.6.1L/nvvib_docs/DRIVE_OS_Linux_SDK_Development_Guide/baggage/group__egl__group.html) for headless rendering. You should be able to add `libOpenGL` and `libEGL` to the `system_packages` of your `cog.yaml` and use something like [pegl](https://github.com/perey/pegl) in your `predict` function.
