### ISSUE TITLE
Cog docker labels for base images have incorrect hashes

### ISSUE THREAD

**Issue by 8W9aG** [replicate/cog#1822]
* When using `--use-cog-base-images` to build a container cog outputs the follow label: `run.cog.cog-base-image-last-layer-sha`.
* This label is filled with a hash that doesn't exist in the docker container.
* In cog `0.9.12` this is correct but in `0.9.13` it appears to be incorrect.

**Comment by mattt** [comment]
This sounds like a regression from https://github.com/replicate/cog/pull/1779.

**Comment by 8W9aG** [comment]
Test case:

[hello-world.tar.gz](https://github.com/user-attachments/files/16365538/hello-world.tar.gz)
```
cog build -t dbg .
docker inspect dbg
```
