### ISSUE TITLE
Can not download cog in WSL2

### ISSUE THREAD

**Issue by jiehwa** [replicate/cog#1840]
![image](https://github.com/user-attachments/assets/92c10118-7ecf-49c4-8069-eb09979f947e)

https://github.com/replicate/cog/blob/main/docs/wsl2/wsl2.md

`sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
sudo chmod +x /usr/local/bin/cog`

when i run this code, it doesn't work

**Comment by 8W9aG** [comment]
What does `echo https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`` give you? We just performed a new release an hour ago so it might be a race condition with github, perhaps you could try giving it another go now?

**Comment by jiehwa** [comment]
> What does `echo https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`` give you? We just performed a new release an hour ago so it might be a race condition with github, perhaps you could try giving it another go now?

![image](https://github.com/user-attachments/assets/0d94100f-8e74-49a4-9754-2b5eac2a0ddf)

The link may be correct, because the link displayed after entering 'echo' in the browser can be used to download the corresponding file. However, I'm not sure if it's a network configuration issue.

**Comment by jiehwa** [comment]
> What does `echo https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`` give you? We just performed a new release an hour ago so it might be a race condition with github, perhaps you could try giving it another go now?

![image](https://github.com/user-attachments/assets/388c3504-e930-4e57-82e4-bd2c2e011e1b)
This could be a network issue, downloading is too slow... The good news is that it is currently downloading.

**Comment by 8W9aG** [comment]
Good news that its downloading. Unfortunately this is hosted by github so we can't do much beyond what they can do with their mirrors. I will close this issue, let me know if you think it should be re-opened.
