### ISSUE TITLE
Unsupported base image configuration

### ISSUE THREAD

**Issue by sonicbaume** [replicate/cog#1845]
I'm trying cog for the first time, but getting a `Failed to generate Dockerfile: unsupported base image configuration` error on what should be compatible configurations.

- macOS 14.2.1
- cog 0.9.14
- Docker 26.1.4

If I copy `cog.yaml` and `predict.py` from the README example and run `cog predict --debug`, I get the following output:

```
Setting CUDA to version 12.1 from Torch version
Setting CuDNN to version 12.1
Building Docker image from environment in cog.yaml...
⚠ Stripping patch version from Torch version 3.12 to 3.12
ⅹ Failed to generate Dockerfile: unsupported base image configuration: CUDA: 12.1 / Python: 3.12 / Torch: 2.2
```

Same with `gpu: false`:

```
Building Docker image from environment in cog.yaml...
⚠ Stripping patch version from Torch version 3.12 to 3.12
ⅹ Failed to generate Dockerfile: unsupported base image configuration: CUDA: (none) / Python: 3.12 / Torch: 2.2
```

Any ideas?

**Comment by mattt** [comment]
Hi @sonicbaume. Sorry for the confusion there, and thank you for pointing this out!

#1655 bumped the instructions to the latest versions of Python and Torch at the time, but that combination isn't supported. If you bump Torch to 2.3 or relax Python to 3.11, that'll build for you.

I opened https://github.com/replicate/cog/pull/1846 to address this issue.

**Comment by sonicbaume** [comment]
Thanks for the quick reply. Your suggested changes to the README example work. However, I'm struggling to get cog to work with the versions I'm interested in:

**cog.yaml:**
```yaml
build:
  gpu: true
  python_version: "3.9"
  python_packages:
    - "torch==1.13.0"
predict: "predict.py:Predictor"
```

```
cog build   
Building Docker image from environment in cog.yaml as cog-enclap-replicate...
⚠ Stripping patch version from Torch version 3.9 to 3.9
ⅹ Failed to get cog base image name: unsupported base image configuration: CUDA: 11.7 / Python: 3.9 / Torch: 1.13
```

This seems to suggest the versions are compatible - is that right?
https://github.com/replicate/cog/blob/d160cc29de9e6eea4932be3a8e3276819feff875/pkg/config/torch_compatibility_matrix.json#L497-L541

Thanks for your help 😊
