### ISSUE TITLE
Docker daemon connection config error in v0.9.14 installed via HomeBrew (Darwin_arm64)

### ISSUE THREAD

**Issue by jbeoris** [replicate/cog#1847]
I consistently get the following error when running `cog build` in v0.9.14 installed via homebrew.

`Failed to ping docker, please try restarting the docker daemon: failed to ping docker, please try restarting the docker daemon: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I tried setting the daemon path differently, but this did not resolve the issue.

I reverted back to v0.9.12 and do not have this issue. It looks like the problem lies in the new daemon pinging logic added in `pkg/docker/ping.go` 5 days ago.

**Comment by jbeoris** [comment]
To clarify the above, Docker Desktop is for sure running and the daemon is available, as proved by the face that `cog build` works perfectly with v0.9.12 and no changes to Docker Desktop.

**Comment by mattt** [comment]
Hi @jbeoris. Sorry this isn't working as expected. Thanks for reporting this.

Curious to know if restarting Docker Desktop and/or your machine changes anything. I'd just like to know if it always produces a false negative. 

/cc @8W9aG

**Comment by jbeoris** [comment]
> Hi @jbeoris. Sorry this isn't working as expected. Thanks for reporting this.
> 
> Curious to know if restarting Docker Desktop and/or your machine changes anything. I'd just like to know if it always produces a false negative.
> 
> /cc @8W9aG

hey, i forgot to respond to this. i even went as far as reinstalling docker and it didn't fix the issue.
