### ISSUE TITLE
Unsupported base image configuration with torch==1.13.0

### ISSUE THREAD

**Issue by sonicbaume** [replicate/cog#1862]
I'm struggling to get cog to work with the versions I'm interested in:

**cog.yaml:**
```yaml
build:
  gpu: true
  python_version: "3.9"
  python_packages:
    - "torch==1.13.0"
predict: "predict.py:Predictor"
```

```
cog build   
Building Docker image from environment in cog.yaml as cog-enclap-replicate...
⚠ Stripping patch version from Torch version 3.9 to 3.9
ⅹ Failed to get cog base image name: unsupported base image configuration: CUDA: 11.7 / Python: 3.9 / Torch: 1.13
```

This seems to suggest the versions are compatible - is that right?
https://github.com/replicate/cog/blob/d160cc29de9e6eea4932be3a8e3276819feff875/pkg/config/torch_compatibility_matrix.json#L497-L541

Thanks for your help 😊

**Comment by 8W9aG** [comment]
It looks like we have the following issues:
1. We do not support anything below Torch 1.13.1 by a hard limit defined in the code: https://github.com/replicate/cog/blob/2a5d7769a5f9e488c5c769c92312e3bee3db6d7b/pkg/dockerfile/base.go#L15
2. When this limit is removed and the compatibility matrix is tested against, it produces an image that does not exist: r8.im/cog-base:cuda11.7-python3.9-torch1.13
3. If this failure happens it cancels the whole build. What we should do here is fallback if the base image option is not explicitly sent.

Will get working on this now.

**Comment by 8W9aG** [comment]
I'll close this, it should be fixed in the next release with the fix that was merged moments ago
