### ISSUE TITLE
inst-colorization build runs out of memory with default Docker for Mac install

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#19]
`pip install` in building GPU image throws OOM with standard 4GB of memory. (Within Docker, not outside.)

**Comment by zeke** [comment]
Is this still relevant? If so, what's the possible fix? Docs about bumping docker's memory allocation?

**Comment by bfirsh** [comment]
We don't use inst-colorization as an example any longer, and we haven't heard this from any users, so let's close I think. If we hear users actually running into this we can fix somehow.
