### ISSUE TITLE
Install packages before pip install

### ISSUE THREAD

**Issue by 8W9aG** [replicate/cog#1949]
Currently we run `pip install` as a build step before `apt-get install`. Some of those python packages depend on those packages but never the other way around, so run this build step first. Add good example is `dlib` which uses `cmake`, we do install `cmake` just after the python dependencies, so it errors because it can't find `cmake`.

**Comment by AlexanderKozhevin** [comment]
has it been released?
I having issue with dlib which depends on cmake
