### ISSUE TITLE
cog is broken because of comment in Dockerfile?!

### ISSUE THREAD

**Issue by bb1** [replicate/cog#2017]
![grafik](https://github.com/user-attachments/assets/780ed1b8-0e34-4dc0-bf7c-f4224f43fb61)
```
> resolve image config for docker-image://docker.io/docker/dockerfile:1.4:
------
Dockerfile:1
--------------------
   1 | >>> #syntax=docker/dockerfile:1.4
   2 |     FROM r8.im/cog-base:cuda12.4-python3.11-torch2.4.1
```

The generator in this line adds a comment which prevent Docker from running the file: https://github.com/replicate/cog/blob/72d7d50fdc987a601ab617c2910a11af784be6b4/pkg/dockerfile/generator.go#L164 
It looks like Docker is interpreting this as the FROM part. 
Can someone just remove this? 
Am I the only one affected?

I tried v0.11.3 and v0.11.0 on Ubuntu.
```
docker --version
Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1
```

**Comment by nickstenning** [comment]
This isn't an issue with cog. It looks like your docker can't retrieve the metadata about the dockerfile format from `docker.io`. Have you tried a `docker logout` and `docker login` to reauthenticate to `docker.io`?

**Comment by nickstenning** [comment]
Closing this issue as this isn't a problem with cog.
