### ISSUE TITLE
Cog MusicGen Fine Tune “Melody” Model Train Upload Error

### ISSUE THREAD

**Issue by dorukhanyaldiz** [replicate/cog#2026]
When I train the model using Replicate through the URL https://replicate.com/sakemin/musicgen-fine-tuner/train, the training process completes without issues when selecting either the “melody” or “stereo melody” versions. However, I encounter the following error:

```
Training failed.
Cog: Got error trying to upload output files
```

I can’t figure out the reason for this error. Since the “melody” and “stereo melody” models have been trained before, I believe I should be able to train them as well.

Could you please assist with identifying the root cause of this issue?

**Comment by aron** [comment]
Thanks for reporting your issue. This isn't a bug with cog but an issue with the server configuration on Replicate's size when trying to upload the very large weights produced by this model. We're working on a fix and I'll update you when it has landed.

**Comment by dorukhanyaldiz** [comment]
Hi Aron,

Thank you for your response. Is there any possibility to upload the model
somewhere else?

Otherwise, Replicate might unfortunately no longer be a suitable platform
for my needs.

Best regards,
Dorukhan

Aron Carroll ***@***.***>, 28 Eki 2024 Pzt, 15:17 tarihinde
şunu yazdı:
