### ISSUE TITLE
Design type system & signature

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#205]
The type system and signature needs some thought.

## User data

- An industry user wants a way of documenting the inputs and outputs of their models so they can figure out how they fit together. Their models use a combination of video, image, and text content with additional metadata that could be represented as JSON.
- We, Replicate, need a type signature to generate forms on Replicate. Specific problems we have encountered:
  - ints and bools are strings
  - There is no image type
  - There are no output types

## Requirements

- We need to define input and output types for a prediction function. It should have some kind of schema (what we currently have at `GET /type-signature`).
- Standard types and custom types (e.g. images, or complex objects) need to be represented.
- Multiple or complex outputs need to be represented somehow. #212 
- It needs to be able to represent files.
- It should support standard REST JSON + HTTP, plus other representations and transports (e.g. gRPC, AMQP)
- Ideally, we want a standard off-the-shelf system (e.g. OpenAPI).

## Potential implementations

We could use OpenAPI / JSON Schema, which would handily generate a self-documenting API, instead of our unnecessarily-invented-here `/type-signature` endpoint. This might happen automatically if we make use of FastAPI in #193. (Hello @zeke!)

A potential issue with this is mixing in files to input/output. There are a few potential solutions: gRPC, multipart forms, references to external files (but how do output files work?). Maybe there is prior art here we can learn from.

## See also

- #193 
- #259 (blocked on / closely related)

**Comment by andreasjansson** [comment]
Another reason for the type signatures to live in Python is that it makes the Cog Python package a standalone thing that can be used and integrated in other places, without using the Cog command line or cog.yaml. For example, if you have a custom Docker image and still want to push to Replicate (https://github.com/replicate/cog/issues/290), or if you want to import someones Predictor class at the Python layer.
