### ISSUE TITLE
Model weights not included in cog push

### ISSUE THREAD

**Issue by enzokro** [replicate/cog#2055]
Hi everyone.

I have a cog project for a Huggingface model that builds locally, and it's working great. I can even run a `cog run bash` command and manually run predictions on a few samples. In this local image, all of the model's weights are present and working.

However, when I push this built image to a cog repository, none of the model weights actually make it. The files that get dropped include those like:
- JSON files.
- .check files.
- .pt files.

I've tried deleting the .cog/ folder, building with no-cache, deleting .dockerignore, etc... Not quite sure where else to go from here. 

One important detail: the model files and folders have a nested structure. For example one of the .pt files that is not surviving the upload lives at this path: `checkpoints/model_artifacts/layout/beehive_v0.0.5_pt/model.pt`. I've tried the `--separate-weights` flag, and will see the following in the docker build stages:
```
COPY --from=weights --link /src/checkpoints/model_artifacts/tableformer /src/checkpoints/model_artifacts/tableformer        0.0s
COPY --from=weights --link /src/checkpoints/model_artifacts/layout/beehive_v0.0.5_pt /src/checkpoints/model_artifacts/layout/beehive_v0.0.5_pt
```

Unfortunately, none of the files make it through.

I've confirmed this by manually by `docker run`'ing one of the uploaded images and, sure enough, the checkpoints/ folder is empty. Hit a wall at this point... is there any further debugging steps I can take to figure this out? 

Thanks so much for the help!

**Comment by enzokro** [comment]
Update: I included the weights as part of the docker build step, using -command: huggingface-cli download.... I placed them somewhere other than /src/checkpoints. Then the weights were included in the push, and it works both locally and via the deployed API. Thanks!

**Comment by iyifr** [comment]
I think this issue can be safely closed.
