### ISSUE TITLE
Pulling `cog-base` during build + push results in 401 Unauthorized

### ISSUE THREAD

**Issue by sourceful-karlson** [replicate/cog#2076]
```console
$ cog push r8.im/exmaple/example
```

```console
> [internal] load metadata for r8.im/cog-base:cuda12.1-python3.10:
------
Dockerfile:2
--------------------
   1 |     #syntax=docker/dockerfile:1.4
   2 | >>> FROM r8.im/cog-base:cuda12.1-python3.10
   3 |     RUN --mount=type=cache,target=/var/cache/apt,sharing=locked apt-get update -qq && apt-get install -qqy  && rm -rf /var/lib/apt/lists/*
   4 |     COPY .cog/tmp/build20241205090736.6594922876286173/cog-0.13.6-py3-none-any.whl /tmp/cog-0.13.6-py3-none-any.whl
--------------------
ERROR: failed to solve: failed to resolve source metadata for r8.im/cog-base:cuda12.1-python3.10: unexpected status from HEAD request to https://r8.im/v2/cog-base/manifests/cuda12.1-python3.10: 401 Unauthorized
ⅹ Failed to build Docker image: exit status 1
```

**Comment by sourceful-karlson** [comment]
This behavior is seen in windown WSL

not the case in my mac m1

**Comment by tempusfrangit** [comment]
Can you share your cog.yaml, there is an odd artifact of a trailing `:` at the end of the metadata resolution. Local testing wasn't able to duplicate a 401 in the same manner, but it could be that we do not have the same `cog.yaml` information.<br><br>Additionally, I would expect a push to `exmaple/example` to fail unless your github username (and authenticaed replicate user) is `exmaple`. <br><br>I can also say confidently there are a lot of edge cases with WSL that will not present on OS X, or other Linux systems (the networking in WSL is particularly funky compared to other virt/baremetal options)

**Comment by sourceful-karlson** [comment]
my cog is same as this one https://github.com/fofr/cog-comfyui

**Comment by sourceful-karlson** [comment]
completely understahnd how hard to make wsl works, i am not blocked at all

**Comment by sourceful-karlson** [comment]
Pushing image 'r8.im/sourceful-official/cog-comfyui-incontext-redux-fill'...
Using default tag: latest
The push refers to repository [r8.im/sourceful-official/cog-comfyui-incontext-redux-fill]
a2fff5163495: Preparing 
3d4772f2b891: Preparing 
262ac4b17387: Preparing 
35d123f4fda0: Preparing 
2df7bc63ec32: Preparing 
35d123f4fda0: Retrying in 14 seconds 
bed7baeb09be: Waiting 
a1618c413269: Waiting 
1171d0256a60: Waiting 
614b54e4da0a: Waiting 
fd1e61b8d9e2: Waiting 
2df7bc63ec32: Retrying in 16 seconds 
11ed4c98262c: Waiting 
3d4772f2b891: Retrying in 4 seconds 
1955763a31a8: Waiting 
ed833d6a9aa1: Waiting 
829efec66bb7: Waiting 
6e11a516b4c8: Waiting 
bed7baeb09be: Retrying in 5 seconds 
552b2b859388: Waiting 
461cf6ba28a4: Waiting 
ff66b339eab4: Waiting 
8fe877b592f0: Waiting 
538b8d249fcb: Waiting 
3439643961e5: Waiting 
4ec8ea6bae9d: Waiting 
5ba64f0247e6: Waiting 
00915ad78379: Waiting 
unknown: {"errors":[{"code":"NAME_UNKNOWN","message":"The model https://replicate.com/sourceful-official/cog-comfyui-incontext-redux-fill doesn’t exist or you don’t have access to it."}]}

**Comment by sourceful-karlson** [comment]
cog file


build:
  gpu: true
  cuda: "12.1"
  system_packages:
    - ffmpeg
  python_version: "3.10.6"
  python_packages:
    - torch
    - torchvision
    - torchaudio
    - torchsde
    - einops
    - transformers>=4.39.3
    - tokenizers>=0.13.3
    - sentencepiece
    - safetensors>=0.3.0
    - aiohttp
    - watchdog
    - accelerate>=1.1.1
    - pyOpenSSL
    - pyyaml
    - Pillow
    - scipy
    - tqdm
    - psutil
    - spandrel
    - soundfile
    - kornia>=0.7.1
    - websocket-client==1.6.3
    - diffusers>=0.31.0

    # Inspire
    - webcolors

    # fix for pydantic issues in cog
    # https://github.com/replicate/cog/issues/1623
    - albumentations==1.4.3

    # was-node-suite-comfyui
    # https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/requirements.txt
    - cmake
    - imageio
    - joblib
    - matplotlib
    - pilgram
    - scikit-learn
    - rembg

    # ComfyUI_essentials
    - numba

    # ComfyUI_FizzNodes
    - pandas
    - numexpr

    # comfyui-reactor-node
    - insightface
    - onnx

    # ComfyUI-Impact-Pack
    - segment-anything
    - piexif

    # ComfyUI-Impact-Subpack
    - ultralytics!=8.0.177

    # comfyui_segment_anything
    - timm

    # comfyui_controlnet_aux
    # https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/requirements.txt
    - importlib_metadata
    - opencv-python-headless>=4.0.1.24
    - filelock
    - numpy
    - scikit-image
    - python-dateutil
    - mediapipe
    - svglib
    - fvcore
    - yapf
    - omegaconf
    - ftfy
    - addict
    - yacs
    - trimesh[easy]

    # ComfyUI-KJNodes
    - librosa
    - color-matcher

    # PuLID
    - facexlib

    # SUPIR
    - open-clip-torch>=2.24.0
    - pytorch-lightning>=2.2.1

    # For train.py
    - huggingface_hub
  run:
    - curl -o /usr/local/bin/pget -L "https://github.com/replicate/pget/releases/download/v0.8.1/pget_linux_x86_64" && chmod +x /usr/local/bin/pget
    - pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
predict: "predict.py:Predictor"

**Comment by sourceful-karlson** [comment]
cog file

`build:
  gpu: true
  cuda: "12.1"
  system_packages:
    - ffmpeg
  python_version: "3.10.6"
  python_packages:
    - torch
    - torchvision
    - torchaudio
    - torchsde
    - einops
    - transformers>=4.39.3
    - tokenizers>=0.13.3
    - sentencepiece
    - safetensors>=0.3.0
    - aiohttp
    - watchdog
    - accelerate>=1.1.1
    - pyOpenSSL
    - pyyaml
    - Pillow
    - scipy
    - tqdm
    - psutil
    - spandrel
    - soundfile
    - kornia>=0.7.1
    - websocket-client==1.6.3
    - diffusers>=0.31.0

    # Inspire
    - webcolors

    # fix for pydantic issues in cog
    # https://github.com/replicate/cog/issues/1623
    - albumentations==1.4.3

    # was-node-suite-comfyui
    # https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/requirements.txt
    - cmake
    - imageio
    - joblib
    - matplotlib
    - pilgram
    - scikit-learn
    - rembg

    # ComfyUI_essentials
    - numba

    # ComfyUI_FizzNodes
    - pandas
    - numexpr

    # comfyui-reactor-node
    - insightface
    - onnx

    # ComfyUI-Impact-Pack
    - segment-anything
    - piexif

    # ComfyUI-Impact-Subpack
    - ultralytics!=8.0.177

    # comfyui_segment_anything
    - timm

    # comfyui_controlnet_aux
    # https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/requirements.txt
    - importlib_metadata
    - opencv-python-headless>=4.0.1.24
    - filelock
    - numpy
    - scikit-image
    - python-dateutil
    - mediapipe
    - svglib
    - fvcore
    - yapf
    - omegaconf
    - ftfy
    - addict
    - yacs
    - trimesh[easy]

    # ComfyUI-KJNodes
    - librosa
    - color-matcher

    # PuLID
    - facexlib

    # SUPIR
    - open-clip-torch>=2.24.0
    - pytorch-lightning>=2.2.1

    # For train.py
    - huggingface_hub
  run:
    - curl -o /usr/local/bin/pget -L "https://github.com/replicate/pget/releases/download/v0.8.1/pget_linux_x86_64" && chmod +x /usr/local/bin/pget
    - pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
predict: "predict.py:Predictor"
`

**Comment by meatballhat** [comment]
@sourceful-karlson Thanks for your patience!
- Are you still consistently seeing this error in WSL?
- If you haven't already, could you try running another `cog login` in the same environment where you are running `cog push`?

**Comment by sourceful-karlson** [comment]
I have done multple cog login, still the same result, it is okay, I will push from my m1 mac

**Comment by sourceful-karlson** [comment]
unknown: {"errors":[{"code":"NAME_UNKNOWN","message":"The model https://replicate.com/sourceful-official/cog-comfyui-incontext-redux-fill doesn’t exist or you don’t have access to it."}]}
ⅹ Failed to push image: exit status 1

**Comment by sourceful-karlson** [comment]
cog version 0.13.6 (built 2024-12-03T16:31:25Z)

**Comment by meatballhat** [comment]
@sourceful-karlson Thank you, and glad to hear you have a workaround available! For the record, we are not planning to pursue supporting WSL right now.
