### ISSUE TITLE
cog push fails with error message: "unexpected status from POST request to https://r8.im/v2/*/*/blobs/uploads/: 403 Forbidden"

### ISSUE THREAD

**Issue by Sagnik2810Sarkar** [replicate/cog#2093]
I am unable to push a model to replicate. Installing cog and docker went smoothly and building the image succeeds but when attempting to push the image I get stuck at:

```
Pushing image 'r8.im/*/*'...
Using default tag: latest
The push refers to repository [r8.im/*/*]
89821186f546: Waiting
b3dc753f43ee: Waiting
060e5cadea63: Layer already exists
a5b4c0c84dfc: Layer already exists
439bb542849d: Waiting
030a08cc51cf: Waiting
89e958295611: Waiting
5f16a1ef3ba8: Waiting
616cc09657b7: Waiting
fb9e7a17b329: Layer already exists
dcb32cfc8285: Layer already exists
4f62df8de016: Waiting
9c069ced2869: Layer already exists
e2432a8794da: Layer already exists
42f59d766c42: Layer already exists
035a7917492c: Layer already exists
c46eff6a7578: Layer already exists
193f558ccd20: Layer already exists
4738f81f33f0: Layer already exists
4a1c197b00a6: Layer already exists
f958dccde038: Waiting
0fda777aa4ea: Layer already exists
72ec2a519b5b: Layer already exists
402538bc3f00: Layer already exists
bf71e149328d: Layer already exists
99d1414ff0be: Waiting
f53d7089987b: Layer already exists
7d392010741a: Waiting
unexpected status from POST request to https://r8.im/v2/*/*/blobs/uploads/: 403 Forbidden
ⅹ Failed to push image: exit status 1
```

As far as I understand this is due to some authorization failure but I can't imagine that happening after a successful login using cog login. Any pointers?

**Comment by Timothy102** [comment]
me too, didn't resolve yet

**Comment by fire** [comment]
Also happens to me.

**Comment by bobyaimodel** [comment]
++

**Comment by fire** [comment]
I figured it out. In docker desktop disable containerd support and cog push will work.

**Comment by Sagnik2810Sarkar** [comment]
> I figured it out. In docker desktop disable containerd support and cog push will work.

Ahh ok i was previously trying to disable the containerd service but couldn't find it active in WSL so i thought it must've been something else. Finally got that it had to be done through docker settings. Thanks for the tip!

**Comment by fire** [comment]
Probably want a issue tracking the upgrade to conainerd thoughh

**Comment by zuriby** [comment]
This.
<img width="1040" alt="Image" src="https://github.com/user-attachments/assets/03476668-21b7-4aa0-b3c8-71698e742ef5" />
