### ISSUE TITLE
reset does not reset the input to default/initial state

### ISSUE THREAD

**Issue by CJWBW** [replicate/cog#256]
Seems the reset button resets the input to the example input rather than to default/initial state. Problem with [this model](https://replicate.ai/arantxacasanova/ic_gan) is that, by default the image is optional and is set to None. I have run the first example with an uploaded image, and seems I cannot remove it anymore to try the input without images.

**Comment by bfirsh** [comment]
Thanks @CJWBW! I've moved this to Notion because this looks to be just a Replicate issue.
