### ISSUE TITLE
Feature request: Add option to cli to output Dockerfile

### ISSUE THREAD

**Issue by ericallam** [replicate/cog#265]
As I was playing around with running cog I found myself curious about what actually went into the Docker image that `cog build` produces. It would be nice to be able to output the Dockerfile that `cog build` produces, as both a learning tool and the ability to "escape hatch" out of cog if necessary.

**Comment by bfirsh** [comment]
cog debug dockerfile

Sssh... don't tell anyone. ;)

**Comment by bfirsh** [comment]
Seriously though -- this should be documented somewhere. Thanks for the request. 😄

**Comment by HitLuca** [comment]
I also wanted to take a look at the Dockerfile and found your code being what I needed. For me there wasn't any particular reason, I just wanted to see what cog does exactly :)

**Comment by zeke** [comment]
Thanks for opening this issue, @ericallam. This is now documented by #474 

@all-contributors please add @ericallam for ideas.
