### ISSUE TITLE
Killing cog predict doesn't kill running Docker container

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#299]
When you C-c the running cog predict command it exits, but the Docker container keeps running in the background. The only way to stop it is `docker stop`.

Cog should catch SIGTERM and kill the Docker container before exiting.

**Comment by dribnet** [comment]
Perhaps a different issue, but I'll note here that if possible closing the browser tab should also send a SIGTERM to the docker container so that the process doesn't continue to use GPU resources on the back end.
