### ISSUE TITLE
documentation doesn't indicate that git+ python dependencies are possible

### ISSUE THREAD

**Issue by alastair** [replicate/cog#313]
The documentation for `build.python_packages` at https://github.com/replicate/cog/blob/main/docs/yaml.md doesn't say that you can use urls starting with `git+` to specify to a package installed directly from a git repository.
We ran into this when a colleague thought that all packages needed to be available on pypi to be able to install them (we have some in-progess packages), and I was only able to determine that cog actually accepts this format of requirements by reading the source.

If you want to be able to pin a specific version even from git, you could require that the requirements line has a hash to check out (i.e. the line contains a `@`). While this wouldn't stop someone from specifying a branch such as master, the documentation could suggest to use a commit or a tag.

**Comment by mattkindy** [comment]
This also requires the following addition to `cog.yaml`:
```yaml
  system_packages:
    - "git"
```

**Comment by mcam10** [comment]
does this still need attention?

**Comment by mattkindy** [comment]
@mcam10 Looks like it is addressed in the current version of the docs

**Comment by mcam10** [comment]
@alastair - can we close this issue out then.. this has been addressed.
