### ISSUE TITLE
Split Python unit tests into multiple files

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#339]
The Python unit tests are in one giant file in `python/cog_test.py`. This would be better as separate files that correspond to the files in `python/cog/`.

I tried doing this and it isn't trivial. Some wrangling of import paths will be needed, perhaps by setting the path in the Makefile, or configuring py.test's import mechanism: https://docs.pytest.org/en/6.2.x/pythonpath.html

**Comment by zeke** [comment]
Resolved in https://github.com/replicate/cog/pull/358 thanks to @VictorXLR ✨
