### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by TarunavBA** [replicate/cog#356]
please upload this package to PyPi and make it installable by command `pip install cog`

**Comment by bfirsh** [comment]
Indeed, we'd love to do that! See #146 #147. If you have any time to help out, it would be very much appreciated :)

**Comment by TarunavBA** [comment]
Sure @bfirsh I would love to maintain it.

**Comment by bfirsh** [comment]
I think step 1 is getting our github actions script to push to pypi on new tag, and maybe also setting some expectations in the pypi readme about what the Python library actually does. Thank you!
