### ISSUE TITLE
Add `-p` to `cog run` to forward ports

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#357]
As mentioned in #123, this should do the right thing:

```
cog run -p 8080:8080 jupyter notebook --ip 0.0.0.0 --no-browser --port=8080 --allow-root
```

It should behave the same as `docker run`'s `-p`.

## Future

Not essential to do from day 1, but we might also benefit from a slight change in behavior. If you only pass one port to Docker (`-p 8080`), Docker will pick a random high port on the host machine. This is normally not what the user wants to do when running programs in development -- they want the port to be the same, known port, because the server inside will display something like `Running on http://localhost:8080` and that should work. And they're usually just running one thing so they won't collide.

So, perhaps `-p 8080` could expand to `-p 8080:8080`. We might need some way to get back the previous behavior, e.g. `-p 8080:` or `-p 8080:auto`.

**Comment by EmilioNicolas** [comment]
Hello! I am interested in exposing a port from my docker container in COG and arrived at this issue. It is supposedly working but this doesn't work

`sudo cog run -p xxxx:xxxx`

Any workaround?
