### ISSUE TITLE
Send full snapshots or incremental updates to AMQP response queue?

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#438]
The original proposal in https://github.com/replicate/cog/issues/404 described an API where Cog's AMQP worker is sending the entire state to the response queue on each update (e.g. a new log line is produced, or intermediate outputs are generated). @evilstreak and I spoke in person about this design and contrasted it with a design where only incremental updates are sent to the response queue.

## Full snapshots

In this design, the response queue is fed with full snapshots that represent the cumulative state of the prediction up to that point in time. Those snapshots are put on the queue every time there is a change to the model. For example, the following predict function
```python
def predict(self):
    print("first log line")
    print("second log line")
    time.sleep(2)
    print("third log line")
    return "output"
```

would send the following messages to the queue (disregarding metrics):

1.
```json
{
  "status": "processing",
  "output": null,
  "logs": ["first log line"]
}
```

2.
```json
{
  "status": "processing",
  "output": null,
  "logs": ["first log line", "second log line"]
}
```

3.
```json
{
  "status": "processing",
  "output": null,
  "logs": ["first log line", "second log line", "third log line"]
}
```

4.
```json
{
  "status": "success",
  "output": {"text": "output"},  # <- exact format tbd
  "logs": ["first log line", "second log line", "third log line"]
}
```

Benefits:
* You can always get a full snapshot of a prediction
* No need for the infrastructure that hosts the Cog models to "merge" states
* The AMQP API messages map 1-1 to the HTTP API. It would be a shame to lose this symmetry -- for documentation, schema, simplicity of writing clients, elegance of internals, etc.

Downsides:
* State cumulatively increases in size
* Lots of duplicated data kept in RabbitMQ
* You might want to forward incremental updates, e.g. to your own logging system. In that case you'd have to manually compute diffs between subsequent response messages
* There’s a lot of output that might never get used if you're not interested in the logs or intermediate outputs
* This design intuitively felt surprising to both of us

## Incremental updates

Instead of sending a full cumulative snapshot of each prediction state to the response queue, we considered a design where we only send incremental updates of what has changed recently.

For efficiency we could batch log lines and only send logs at a fixed interval. Progressive outputs and final results would still be sent as soon as they are produced by the model.

The predict function above would produce the following messages:

1.
```json
{
  "status": "processing",
  "output": null,
  "logs": ["first log line", "second log line"] # <- batched
}
```

2.
```json
{
  "status": "processing",
  "output": null,
  "logs": ["third log line"] # <- only one new log line
}
```

3.
```json
{
  "status": "success",
  "output": {"text": "output"},
  "logs": []
}
```

Benefits:
* No duplicated data between messages
* Message sizes don't indefinitely grow larger depending on the number of messages
* Easier to forward logs to log processors

Downsides:
* User of Cog models may need to manually "merge" incremental updates into actual prediction states. In the example above, at timestep 2 `["third log line"]` would have to be concatenated with the existing log line array, and at timestep 3 the status would have to be updated to "success" and output overwritten by `{"text": "output"}`.

---

This issue was originally raised in https://github.com/replicate/cog/issues/404.

**Comment by bfirsh** [comment]
This is being presented as a dichotomy, but I think there may be a more elegant third design we can find here.

I have also added another downside 

Something that got lost from #404 that is still relevant, I think:

> The only field which seems to be special here is log messages. Most users of Cog don't care about logs in the model output, like @CtrlC-Root mentioned. Logs would usually be shipped off directly to logging systems from the model via K8S, Docker log adapters, etc.
> 
> If most people don't care about getting their output live, logs should probably not be sent by default. We could have some option for enabling it.
> 
> This is making me wonder if logs would actually work better as a separate type of message, or a separate queue, like we have at the moment? Or maybe even just some completely separate system? (Just ship to syslog?!)

One potential design is where the API response represents the state of the prediction (status, output, etc), and logs are shipped using an entirely different system (maybe piped directly to replicate-web?).

This seems to hit all the benefits of both approaches, in additional to not shipping logs by default when most users probably don't care about them. We avoid duplicated messages, merging output objects, and retain the elegance of sharing request/response objects between the APIs. (This will be a big win for documentation, users understanding the API, and implementing client libraries.)

**Comment by sirupsen** [comment]
At a high-level, my take here would be:

If you're streaming, incremental
If you're asking for status of a prediction via a polling API, everything (up to a truncated limit)

I like logging being included for ease of debugging when you're just getting started

... and yes, certainly with a flag to allow it to go to `stderr` -- preferably we don't write logging adapters, just provide `stderr`.

**Comment by evilstreak** [comment]
We're going to go with full snapshots:

- it's easier to use
- it matches the HTTP API 

We'll plan to add log truncation and flag to send logs to `stderr` to improve situations where certain models produce a lot of logs, or where folks want to centrally collect all the logs for multiple workers.
