### ISSUE TITLE
document `cog.Path` and `cog.File`

### ISSUE THREAD

**Issue by zeke** [replicate/cog#445]
The new [pydantic version of Cog](https://github.com/replicate/cog/pull/407) includes two new custom input types `cog.Path` and `cog.File`. These should be documented in the [Python API doc](https://github.com/replicate/cog/blob/80bc64945e1e4f78fdd691c9746adfcfd0f6c8b2/docs/python.md#inputkwargs).

- `cog.File`: a file-like object representing a file
- `cog.Path`: a path to a file on disk

**Comment by zeke** [comment]
Note: `cog.Path` extends `pathlib.Path`, so model others can use it as as stand-in replacement for Python `Path` they're used to.

**Comment by bfirsh** [comment]
#452
