### ISSUE TITLE
Document how to use a Jupyter notebook with Cog

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#488]
We should have some basic documentation on how to run a Jupyter notebook in a Cog environment. Most researchers work in notebooks, so we need a story around this.

Could just be as simple as implementing #357 and documenting the command in the getting started guide or somewhere like that:

```
cog run -p 8080 jupyter notebook --ip 0.0.0.0 --no-browser --port=8080 --allow-root
```

Implements #123

See also https://github.com/replicate/cog/issues/357

edited by @zeke

**Comment by zeke** [comment]
Resolved by https://github.com/replicate/cog/pull/524
