### ISSUE TITLE
document that `cog.Input()` is not required when defining a predictor

### ISSUE THREAD

**Issue by zeke** [replicate/cog#539]
I was under the impression that using [`cog.Input()`](https://github.com/replicate/cog/blob/main/docs/python.md#inputkwargs) was **required** when defining parameters to the `predict` method in pydantic Cog predictors. But then I noticed in our integration tests that a number of our test predictors don't use it. For example:

This predictor is valid:
```py
from cog import BasePredictor

class Predictor(BasePredictor):
    def predict(self, input: str) -> str:
        return "hello " + input
``` 

and produces this schema:

```json
{
  "components": {
    "schemas": {
      "Input": {
        "title": "Input",
        "required": ["input"],
        "type": "object",
        "properties": {
          "input": {
            "title": "Input",
            "type": "string",
            "x-order": 0
          }
        }
      },
      "Output": {
        "title": "Output",
        "type": "string"
      }
    }
  }
}
```

It seems like this should be documented, so users know that `Input` is optional.

Is there some reason why we would want to discourage users from defining simple inputs that don't use `cog.Input()`?

**Comment by zeke** [comment]
Looks like the default value is handled here: https://github.com/replicate/cog/blob/684c735335d8a51676ab6b611d8535572ae8dd93/python/cog/predictor.py#L124-L131

**Comment by bfirsh** [comment]
> Is there some reason why we would want to discourage users from defining simple inputs that don't use cog.Input()?

Nope, and this is intentional! Philosophically, we're trying to lean on vanilla Python as much as possible and only use these functions if additional information is required. `input: str`, `input: str = "default"` should all work. Same as Pydantic.
