### ISSUE TITLE
Error when trying to run a notebook on a sample project

### ISSUE THREAD

**Issue by iperdomo** [replicate/cog#560]
Hi,

The documentation suggests that I should be able to run a jupyter notebook by issuing a `cog run jupyter [...]` command - See #488

I'm testing Cog version 0.3.0 and I'm getting the following error in a fresh sample project:
```
[...]
Running 'jupyter notebook --ip 0.0.0.0 --no-browser --port=8080 --allow-root' in Docker with the current directory mounted as a volume...
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "jupyter": executable file not found in $PATH: unknown.
ⅹ exit status 127
```

### Environment
* OS: Ubuntu 22.04 LTS
* Docker: 20.10.14, build a224086
* Cog: 0.3.0 (built 2022-04-20T15:43:04Z)

### Steps to reproduce
* Download Cog as per [installation instructions](https://github.com/replicate/cog/tree/v0.3.0#install=)
* Create a sample project: `cog init`
* Attempt to launch jupyter with: `cog run -p 8080 jupyter notebook --ip 0.0.0.0 --no-browser --port=8080 --allow-root`

See attached video

https://user-images.githubusercontent.com/178474/164511281-1791c929-e498-44fc-b6ec-a5652b0aa964.mp4

**Comment by zeke** [comment]
Hey @iperdomo thanks for reporting this, and for include that helpful video to illustrate the problem. ⭐ 

In order to run the `juptyer` command, you'll need to add the `jupyterlab` dependency to your `cog.yaml` file, like so:

```yml
build:
  python_packages:
    - "jupyterlab==3.3.4"
```

You should then be able to `cog build` then run the notebook command above.

I will open a PR to update the documentation around this.

**Comment by iperdomo** [comment]
Hi @zeke thanks for the explanation, that was my guess. You have to install `jupyter` as part of the dependencies. Adding jupyter to the dependencies make the docker image even bigger, and you don't _need_ jupyter in the production image, just for development.

It would be interesting to define the _scope_ of the package, e.g. production vs development. Different ecosystems solve the issue in different ways, e.g. `npm` with [devDependencies](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#devdependencies). I'm not sure if there is way to specify _dev_ dependencies with `pip`

**Comment by zeke** [comment]
@all-contributors please add @iperdomo for bugs
