### ISSUE TITLE
Running cog docker on a different port / Running multiple instances of a cog container

### ISSUE THREAD

**Issue by programmeddeath1** [replicate/cog#621]
Is it possible to run a created cog docker on a different port than 5000. I want to know if I can run multiple instances of the created docker on different ports for handling multiple parallel requests based on the transactions per second in production.

I checked documentation for info regarding this but I didnt find it, I read a few times, sorry if I missed something while reading.

Thanks for your reply in advance!

**Comment by bfirsh** [comment]
Hello @programmeddeath1! You can indeed, if you're running the containers with `docker run` directly.

[With the example on this page], the first port number in the `-p` option is the port exposed on your machine. So you can run multiple of them like this:

```
docker run -d -p 5000:5000 ...
docker run -d -p 5001:5000 ...
docker run -d -p 5002:5000 ...
```

And so on.

Out of interest, what kind of model are you deploying and how are you deploying it? Is it all on a single machine and you're manually running these `docker run` commands?

**Comment by programmeddeath1** [comment]
Hi @bfirsh  sorry for not mentioning this while raising the question before, i raised it in a hurry without context.
I had ran this before directly using ```docker run -d -p 5001:5001 container_name```, but it is still hosting it on port 5000. the tcp port on the docker shows 5000/tcp. I even tried different ports 6000:6000

![image](https://user-images.githubusercontent.com/44861370/169450427-d7706353-1db3-4b95-a6de-1132276ca6b0.png)

This is what I found weird and hence raised this issue. Whatever port i gave, the cog container mapped it to 5000 port and the log shows uvicorn running on http://0.0.0.0:5000

![image](https://user-images.githubusercontent.com/44861370/169451346-228e0bf8-7795-432b-8f6a-161ffc79c6ee.png)

**Comment by programmeddeath1** [comment]
Its a zeroshot transformer model that I am deploying to a single aws machine. Since I am running on a non-GPU server, i am running  parallel instances to serve multiple requests at a time. 
For now I am simply testing this setup and its feasibility. In production mostly the docker runs  and deployment will be triggered through scripts.

**Comment by programmeddeath1** [comment]
Thank you that was it. I was running the container  on a different port too which was causing the problem.
