### ISSUE TITLE
Support non-interactive `cog login`

### ISSUE THREAD

**Issue by zeke** [replicate/cog#637]
The `cog login` command is currently interactive: You have to switch to a browser to copy a token, then paste it in the terminal. This flow won't work in CI environements.

Let's update Cog to look for an auth token in the environment, so we can do `cog push` from a GitHub Actions workflow!

**Comment by bfirsh** [comment]
fixed in #731

**Comment by zeke** [comment]
Aw sweet!

```
echo $REPLICATE_TOKEN | cog login --token-stdin
```
