### ISSUE TITLE
Redis issue causing CI to fail

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#671]
Logs are too long to display on GitHub actions but this is the error:

```
Failed to handle message: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cog/server/redis_queue.py", line 166, in start
    message_id, message_json = self.receive_message()
  File "/usr/local/lib/python3.8/site-packages/cog/server/redis_queue.py", line 128, in receive_message
    key, raw_message = raw_messages[0]
ValueError: too many values to unpack (expected 2)
```

I thought it might be that [the redis 7 docker image was pushed a few days ago](https://hub.docker.com/layers/redis/library/redis/7.0/images/sha256-31120dcdd310e9a65cbcadd504f4fe60a185bd634ab7c6a35e3e44a941904d97?context=explore) but pinning to `redis:6` doesn't seem to fix it.

**Comment by andreasjansson** [comment]
Something has changed between `redis==4.3.3` and `redis==4.3.4`. If I downgrade to 4.3.3 things work as before. Tested locally with https://github.com/replicate/cog-redis-example and a custom build of Cog.
