### ISSUE TITLE
The example imgs cannot be shown in the showcase gallery

### ISSUE THREAD

**Issue by sczhou** [replicate/cog#717]
Hi, 

I test some images in my model (https://replicate.com/sczhou/codeformer), there are some link errors. The errors could appear in the following places:
1. https://replicate.com/explore
![image](https://user-images.githubusercontent.com/14334509/189277660-5393d0b7-9e4c-4ac2-afd4-a3ef8445076d.png)

2. https://replicate.com/sczhou
![image](https://user-images.githubusercontent.com/14334509/189279041-76b42e47-5271-4b27-b2a4-917f28e3126a.png)

3. https://replicate.com/sczhou/codeformer
![image](https://user-images.githubusercontent.com/14334509/189518628-33b6cbeb-3676-4f0a-9ff2-3d2ecc1e9057.png)

---

I checked all three errors should be caused by wrong links,  e.g.,
`/api/models/sczhou/codeformer/files/https://replicate.com/api/models/sczhou/codeformer/files/4e7adcc7-eb0d-49c9-81e5-56c041f7a9dd/output.png`
should be:
`/api/models/sczhou/codeformer/files/4e7adcc7-eb0d-49c9-81e5-56c041f7a9dd/output.png`

![image](https://user-images.githubusercontent.com/14334509/189518737-2beb0c3e-8725-4763-a59a-7eef2c9500dc.png)

And output path in the `predict.py` file (https://github.com/sczhou/CodeFormer/blob/master/predict.py#L146) should be accurate. 

I don't know how to fix this link error, could you help me with that or have any ideas? Thanks!

**Comment by bfirsh** [comment]
This should be fixed now. Sorry about that!

**Comment by sczhou** [comment]
@bfirsh It works. Thank you so much!
