### ISSUE TITLE
Output images Not showing on Replicate explore and Example section in overview page, but work in Example Gallery

### ISSUE THREAD

**Issue by chenxwh** [replicate/cog#718]
For this demo https://replicate.com/sczhou/codeformer,
Output images are not displaying in the explore page and the example section of the overview page of the demo - but they do show up in the example gallery https://replicate.com/sczhou/codeformer/examples. 

See details [here](https://github.com/sczhou/CodeFormer/pull/28#issuecomment-1241519397) 

This demo also has this issue https://replicate.com/cjwbw/stable-diffusion-high-resolution

**Comment by bfirsh** [comment]
This is a replicate issue so will open internally.

**Comment by SkFardinPhoto** [comment]
![1690140175190](https://github.com/replicate/cog/assets/126498813/f8def4d5-2dc0-4dc4-9498-93c6f2482c72)
