### ISSUE TITLE
Handle crashes and OOMs in Redis worker

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#722]
Now that we're running the prediction in a separate subprocess, we can monitor the state of that from outside. When we detect that the prediction process has exited (due to OOM or random crashes) we should send a terminal failed status to the output queue/webhook and terminate the main process. On Replicate, that will then spin up a new fresh pod.

**Comment by evilstreak** [comment]
This is done as of https://github.com/replicate/cog/pull/795
