### ISSUE TITLE
Fail to do cog push 

### ISSUE THREAD

**Issue by MenghanXia** [replicate/cog#733]
After going through local test, I come to a problem at push an image stage. It gets stuck at retrying to push but finally exit with status 1.

![exit](https://user-images.githubusercontent.com/21290345/192187470-5e3ac560-4f02-42ec-8c86-ef4c44e704f3.png)

It seems to be a role authentication problem but I have already successfully passed cog login. Anyone know how to solve it?

**Comment by krrishdholakia** [comment]
I know it's a bit late, but can you paste your stacktrace? @MenghanXia
