### ISSUE TITLE
Don't Know How to use it.

### ISSUE THREAD

**Issue by mm132** [replicate/cog#736]
Don't know how to work it, I have python installed but I don't know how to use it and I really want to be able to run the text-to-pokemon thing.

**Comment by zeke** [comment]
Hi @mm132. Sorry you're having trouble. Here are some pointers to get you on the right track:

1. Check out the prerequisites for running Cog: https://github.com/replicate/cog#prerequisites
1. If you meet those prereqs, install Cog: https://github.com/replicate/cog#install
1. Head to https://replicate.com/lambdal/text-to-pokemon and click on "Run on your own computer". There you'll find an example cog command you can use to run the model:

```
cog predict r8.im/lambdal/text-to-pokemon@sha256:3554d9e699e09693d3fa334a79c58be9a405dd021d3e11281256d53185868912 \
  -i prompt=... \
  -i num_outputs=... \
  -i num_inference_steps=... \
  -i guidance_scale=... \
  -i seed=... 
```

If you're still stuck, you can join our Discord and get help there: https://discord.gg/replicate
