### ISSUE TITLE
Local image management

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#80]
As part of implementing local mode and on server (#18) we need a sensible way of managing local images.

## Requirements

- Tags should not grow uncontrollably, so that images can be cleaned up by `docker system prune`
- The image should be given a name so you can identify it in `docker images`
- The previous image should be removed

For clarity, this is additional work on top of #18. This also includes picking a sensible name when running locally and you aren't pointed at a registry.

**Comment by bfirsh** [comment]
For Compose, we generated a human-readable image name for built images based on the current directory. E.g. if you had a service called `web` as part of `cog`, it would call the image `cog_web`. When you built that image again, it would just overwrite the tag. It would also set labels so there were machine readable versions (`com.docker.compose.project`, `...service`, etc), because parsing the image name is gnarly 

This had a few neat properties:

- Building same image would be idempotent (would just hit the cache and tag the image again)
- When a new image was built, it would untag the old image so it can be garbage collected
- Images in use would not be garbage collected
- The human readable name would show up in `docker images` so you know what is what

The only thing missing from Compose was automatic garbage collection of old images. It could totally do that if it kept a pointer to the image before building, then removed the old image if the ID changes.

Maybe the requirements are different here for the server.

**Comment by bfirsh** [comment]
#119 brings us closer to this getting fixed, but we still need to tag local images in a sensible way.

**Comment by bfirsh** [comment]
Going to close this because it encompassed a few things, and by building base images in #155, this seems to have fixed the painful problem of continually running out of disk space.

I have run out of disk space a couple of times recently, but it's much less often than it used to be. @andreasjansson @zeke have you run out of disk space recently?

#192 may also help mitigate this.

**Comment by zeke** [comment]
> have you run out of disk space recently?

I have not, though I'm on a new machine.

**Comment by bfirsh** [comment]
Superceded by #258
