### ISSUE TITLE
SIGTERM doesn't interrupt setup for Redis queue worker

### ISSUE THREAD

**Issue by evilstreak** [replicate/cog#806]
The worker will exit as expected, but only after setup has completed. For models with long setups this is unnecessarily wasteful. With the new worker internals listening for heartbeat events and checking `should_exit` should be pretty straightforward.

**Comment by varshneydevansh** [comment]
Is this issue still in progress? I am excited to contribute to this project.

**Comment by mattt** [comment]
Closing, because as of https://github.com/replicate/cog/pull/989, Cog no longer depends on Redis.
