### ISSUE TITLE
Set python package version explicitly and expose in package

### ISSUE THREAD

**Issue by nickstenning** [replicate/cog#816]
The cog python package sets version metadata but this has never been updated:

```python
In [1]: from importlib.metadata import version

In [2]: version('cog')
Out[2]: '0.0.1'
```

In addition, there's no `__version__` property on the package. This isn't essential but it would be nice to have this too:

```python
In [3]: import cog

In [4]: cog.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [4], line 1
----> 1 cog.__version__

AttributeError: module 'cog' has no attribute '__version__'
```

It would be really nice to do this in a way that:

- returns the same version from both of the above
- returns the tagged version in tagged builds (e.g. `0.3.4`)
- appends git metadata when not on a tagged build (e.g. `0.3.4-dev+630e696`)

**Comment by nickstenning** [comment]
Some prior art for the fetching version from git bit of this (note that this is from a repo that doesn't have a need for tagged builds): https://github.com/hypothesis/h/blob/main/h/_version.py

**Comment by zeke** [comment]
Some other prior art for how this is done in the `replicate` Python client: https://github.com/replicate/replicate-python/commit/6ffed387d6616fecb5e6e439de671fe87d903c3f
