### ISSUE TITLE
Create Homebrew formula

### ISSUE THREAD

**Issue by mattt** [replicate/cog#822]
[Homebrew](https://brew.sh) is a popular way to install developer tools on macOS. It would be great to be able to install `cog` in a single command, like this:

```console
$ brew install cog
```

**Comment by zeke** [comment]
> 1. Can either of you please cut a release when you have a chance?

Fine by me! We've historically kept the main branch releasable, but we've recently had a few situations where changes accumulated on main that required a bit of team coordination before releasing. @evilstreak @bfirsh @nickstenning are we out of the woods now that 0.5.0 has shipped?

**Comment by zeke** [comment]
Hey @mattt. Sorry the delay. I cut a new release! You should be good to go.

https://github.com/replicate/cog/releases/tag/v0.5.1
