### ISSUE TITLE
Document all the environment variables

### ISSUE THREAD

**Issue by zeke** [replicate/cog#829]
There are a handful of environment variables that can be used to configure Cog's behavior. We should document them all in one place.

From a quick search, I found these:

- `CGO_ENABLED`
- `COG_LOG_LEVEL`
- `COG_NO_UPDATE_CHECK`
- `OTEL_SERVICE_NAME`
- `PORT `

**Comment by theotherjenkutler** [comment]
Can someone point me to the existing documentation of COG_LOG_LEVEL?

**Comment by joannejchen** [comment]
Hi! @scotran and I are part of a Virtualization class at the University of Texas at Austin, and we would like to try to tackle this issue for a school project.

**Comment by ander-db** [comment]
I've tried to figure out what `ports` do, but have been unable to. It's the same funcionality as `docker-compose` (to define which ports expose from the container)?

**Comment by joannejchen** [comment]
Is there any specific markdown file in the repository that I should document these environment variables in?

**Comment by zeke** [comment]
> Is there any specific markdown file in the repository that I should document these environment variables in?

There is not, but you could introduce one! Maybe `docs/environment.md`?

**Comment by joannejchen** [comment]
I created a pull request with the environment variables I was able to find and their functionalities! Let me know if I need to update anything -- e.g. if anything is inaccurate, if there are any environment variables I missed, or more information should be provided for certain variables.

Specifically, I found these environment variables being used, but I couldn't really discern where or how these were being used if you could provide any further guidance: https://github.com/replicate/cog/blob/be661dcf719118e5ec07d00a307ea96223e60c30/python/cog/director/monitor.py#L17-L23.
