### ISSUE TITLE
Could not load dynamic library 'libcudart.so.11.0'

### ISSUE THREAD

**Issue by northfoxz** [replicate/cog#845]
Hello, when I'm running the [example model](https://github.com/replicate/cog/blob/main/docs/getting-started.md), I got the error message in the title and the inference runs on my CPU instead.

1. OS and hardware: Ubuntu 18 with Nvidia 3090 graphics card
2. `cog predict -i image=@input.jpg` with error message `Could not load dynamic library 'libcudart.so.11.0'`

Please check on this, thank you!

**Comment by krrishdholakia** [comment]
The error message you received indicates that the CUDA driver is missing from your system. This is required to run inference on the GPU. To fix this, you can either install the latest CUDA driver from the NVIDIA website, or you can set the environment variable CUDA_VISIBLE_DEVICES to -1 to run the inference on the CPU.

You can set the environment variable CUDA_VISIBLE_DEVICES to -1 by adding the following line to your .bashrc or .profile file: export CUDA_VISIBLE_DEVICES=-1. You can also set the environment variable directly from the command line by running: export CUDA_VISIBLE_DEVICES=-1.

Let me know if that helps! 

Got this from Clerkie (ai code debugger bot) - https://sinfulvibrantexponents.krrishdholakia.repl.co/
