### ISSUE TITLE
Keeping the homebrew formula up to date

### ISSUE THREAD

**Issue by zeke** [replicate/cog#850]
`brew install cog` is a thing now! See https://github.com/replicate/cog/pull/849 and https://github.com/Homebrew/homebrew-core/pull/117929

It looks like it's [pinned at 0,5.1](https://github.com/Homebrew/homebrew-core/blob/1fdce20960fedc5cd7dbcde09c27e029a7dcac22/Formula/cog.rb#L4). How should we go about keeping that up to date as we release new versions of Cog? My guess at a couple options:

- We bump that number whenever we do a release. Does that mean opening a PR on homebrew-core each time? 😬 
- We point it at a tarball off the main branch, then promise ourselves to keep main stable. Then we'd never have to update the formula. Too yolo maybe?

**Comment by zeke** [comment]
cc @mattt

**Comment by zeke** [comment]
Sounds like a plan 👍🏼

**Comment by nickstenning** [comment]
Unfortunately in this case `cog<0.6.0` is likely to be completely broken for everyone thanks to those Interesting Decisions:tm: made at nvidia.

That said, I doubt that hordes of people are already relying on homebrew for cog, so I'm ok with us waiting if we want.

**Comment by zeke** [comment]
> The `cog` formula was bumped to 0.6.1 [two days ago](https://github.com/Homebrew/homebrew-core/pull/118423) by a homebrew-core maintainer,

Nice! Let's call this done then, and revisit if we ever need to.
