### ISSUE TITLE
Run commands without a GPU

### ISSUE THREAD

**Issue by zeke** [replicate/cog#867]
### The problem

I'm [working on a GitHub Actions workflow](https://github.com/replicate/cog-stable-diffusion/pull/68) to `cog push` a model to Replicate. Part of the release process includes running a script to download weights:

```console
cog run script/download-weights
```

Unfortunately that script can't be run in the Actions workflow, because GitHub's hosted runners don't (yet?) have GPUs, and this model has `gpu: true` set in it's `cog.yaml` file. But there isn't anything in the [`download-weights` script](https://github.com/replicate/cog-stable-diffusion/blob/main/script/download-weights) that specifically requires a GPU to run. The current workaround is to approximate the Cog environment by manually installing Python, installing Python dependencies, etc, but that's a pain.

## A possible solution

It would be nice to be able to run one-off cog commands and somehow specify that the GPU is not needed:

```console
cog run script/download-weights --no-gpu-needed-thanks
```

**Comment by bfirsh** [comment]
Builds work without a gpu. There's logic that can be reused there.

**Comment by anotherjesse** [comment]
being able to build and test on a mac seems like it is an issue hitting some folks on discord

**Comment by bfirsh** [comment]
Dupe https://github.com/replicate/cog/issues/590
