### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by arnavmehta7** [replicate/cog#897]
Hi, I had one issue in the code. And I changed it, but whenever I am trying to build the code by running `sudo make install` after `make` it never runs. I have `go` installed but still it give me some errors.

```
/bin/bash: line 1: go: command not found
/bin/bash: line 1: go: command not found
install -m 0755 cog /usr/local/bin/cog```

when I run `go version` I get:
```go version go1.18.3 linux/amd64```

**Comment by mattt** [comment]
Hi @arnavmehta7. I'm sorry to hear that you're having trouble building from source. Please run the following commands on your machine and share the output:

```console
$ which go                      # reports location of Go executable in PATH
$ which python                  # reports location of Python executable in PATH
$ make make VERBOSE=1 clean cog # make cog from clean state
$ ./cog --version               # run cog executable created from previous step
```

**Comment by arnavmehta7** [comment]
Thanks. I have fixed this. I had to add `go` path in visudo.
