### ISSUE TITLE
Add `--package-manager` flag to `cog init` subcommand

### ISSUE THREAD

**Issue by mattt** [replicate/cog#906]
Previously discussed in https://github.com/replicate/cog/issues/157#issuecomment-1408428881

We should make `python_requirements` the default behavior in `cog init` going forward. 

To accomplish this, I propose that we add a new `--package-manager` flag to `cog init`. At first, it would have a single possible value, `pip` (the new default). In the future, we can support other ecosystems by adding acceptable values. For example, running `cog init --package-manager=conda` would generate a project with an `environment.yml` file.

**Comment by bfirsh** [comment]
Do we need this to be able to switch to `python_requirements`? Why couldn't we just change it?

**Comment by mattt** [comment]
Yeah, we could just change it outright. If there's any reason at all that someone would choose to inline their dependencies into `cog.yaml`, we should provide some backwards compatibility with a `--package-manager=cog` option (that's the missing context).

**Comment by bfirsh** [comment]
Got it. I don't _think_ there's a reason. If there isn't, then we can just deprecate it.
