### ISSUE TITLE
cog-quickstart example fails on M1 Mac

### ISSUE THREAD

**Issue by anilmurty** [replicate/cog#958]
Just tried running through https://github.com/replicate/cog/blob/main/docs/getting-started.md on a Mac M1 pro (MacOS Monterey v12.2.1) and got this error:
```
Starting Docker image cog-cog-quickstart-base and running setup()...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped
ⅹ Failed to get container status: exit status 1
```
I wonder if it is because cog is missing the correct buildx option? https://github.com/replicate/cog/blob/75b7802219e7cd4cee845e34c4c22139558615d4/pkg/docker/build.go#L72 

Note that buildx does not seem to support linux/arm/v8
```
% docker buildx ls
NAME/NODE       DRIVER/ENDPOINT STATUS  PLATFORMS
desktop-linux   docker                  
  desktop-linux desktop-linux   running linux/arm64, linux/amd64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
default *       docker                  
  default       default         running linux/arm64, linux/amd64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```

**Comment by konstantin-frolov** [comment]
Same issue. In all versions before 0.7.0-dev.
```No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

go version go1.20.5 linux/amd64

cog version v0.7.0+dev (built 2023-06-08T16:34:43+0300)
```

**Comment by konstantin-frolov** [comment]
> Same issue. In all versions before 0.7.0-dev.
> 
> * Error
> 
> ```
> => exporting cache                                                                                                                                                                                                                     0.0s
>  => => preparing build cache for export                                                                                                                                                                                                 0.0s
> Adding labels to image...
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "/usr/local/lib/python3.8/site-packages/cog/__init__.py", line 1, in <module>
>     from pydantic import BaseModel
>   File "pydantic/__init__.py", line 2, in init pydantic.__init__
>   File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
>     # +---------+-----------------------------------------+
> ImportError: cannot import name dataclass_transform
> 
> ⅹ Failed to get type signature: exit status 1
> ```
> 
> * Host spec
> 
> ```
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.4 LTS
> Release:        20.04
> Codename:       focal
> 
> go version go1.20.5 linux/amd64
> 
> cog version v0.7.0+dev (built 2023-06-08T16:34:43+0300)
> ```

Solved by updating python `typing-extensions`.
Add in `cog.yml`
```
  run:
    - pip install typing-extensions --upgrade
```

**Comment by mattt** [comment]
Hi @stellanhaglund. Thanks for reporting this. We're tracking this issue in https://github.com/replicate/cog/issues/336.

@konstantin-frolov The error you're reporting appears to be unrelated to the original issue. Please see https://github.com/replicate/cog/issues/1007 for details.

**Comment by levelingup** [comment]
I think changing the version of tensorflow to 2.13.0 fixed the error issue.

**Comment by zeke-john** [comment]
I tried using `tensorflow==2.13.0` and still have gotten the same error

Info: `Darwin Zekes-MacBook-Air.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64`

Any update?

![image](https://github.com/replicate/cog/assets/67245013/75ba5e84-1e74-4cd0-b0c4-e55fb112f9b0)

**Comment by smandalika** [comment]
This is the exact same problem I'm having. I'm running cog on M3 Mac OS: 14.2.1 (23C71)
<img width="1512" alt="Screenshot 2024-04-14 at 10 37 30 PM" src="https://github.com/replicate/cog/assets/273031/0fbdd185-90ac-44c3-929c-fcfabb0674b5">

**Comment by qzchenwl** [comment]
The failure is due to Docker on Apple Silicon (ARM) running an x86 image, as indicated by the Warning message. When ARM Docker executes an x86 image, importing ResNet50 fails.

This can be reproduced as follows:
```
cog-quickstart % docker run -it --rm cog-quickstart-base bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
root@72a125bc9dce:/src# python
Python 3.11.10 (main, Sep  9 2024, 18:05:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.keras.applications.resnet50 import ResNet50
Illegal instruction
```

The solution is for Cog to provide an ARM version of the base image `r8.im/cog-base:python3.11`.
```
cog-quickstart % cog debug
#syntax=docker/dockerfile:1.4
FROM r8.im/cog-base:python3.11
COPY .cog/tmp/build20240915011426.4144722118698427/requirements.txt /tmp/requirements.txt
ENV CFLAGS="-O3 -funroll-loops -fno-strict-aliasing -flto -S"
RUN pip install --no-cache-dir -r /tmp/requirements.txt
ENV CFLAGS=
WORKDIR /src
EXPOSE 5000
CMD ["python", "-m", "cog.server.http"]
COPY . /src
```
