### ISSUE TITLE
Cog redownloads model every time Predict is run

### ISSUE THREAD

**Issue by tbukfrc** [replicate/cog#987]
Hello, I am using cog for the first time with https://github.com/rmokady/CLIP_prefix_caption, and every time I want to run a prediction (`sudo cog predict -i @image.jpg`) it has to redownload 1GB of models, which both takes a long time and uses a lot of bandwidth. Cog should be able to cache and load the files locally.

**Comment by arandaks** [comment]
Hi! Can you share your `predict.py`  file?

**Comment by tbukfrc** [comment]
This can be closed. I found out it was HuggingFace Transformers downloading models, so I ran the predict.py file outside of cog, found out where it was downloading every file, and moved them all to the root alongside predict.py and told HuggingFace that was the new cache location. It’s not a pretty solution, but the issue isn’t the fault of Cog (technically).
